import type { ContractItem } from "./contract.schema";

import { contractStatus } from "../../config";

// Демо-данные договоров. Будут заменены ответом API при подключении.
export const contractsMock: ContractItem[] = [
  {
    id: 1,
    contractNumber: "PC-2025-001",
    contractSum: 12500000,
    supplierId: "101",
    constructionType: "Новое строительство",
    contractDate: new Date("2025-01-15"),
    fixedAssetsPlanItem: "ОС-001",
    isRegisteredInTreasury: true,
    contractNotes: "Основной договор",
    parentContractId: null,
    contractTerms: "50% предоплата, 50% после поставки",
    plannedDeliveryDate: new Date("2025-06-30"),
    procurementMethodDetailId: 1,
    contractStatus: contractStatus.ACCEPTED,
    buyerId: 1,
    buyer: {
      id: 1,
      fullName: "АО Кыргызнефтегаз",
      shortName: "КНГ",
      isActive: true,
    },
    quarterDistribution: [],
  },
  {
    id: 2,
    contractNumber: "PC-2025-002",
    contractSum: 8700000,
    supplierId: "102",
    constructionType: "Реконструкция",
    contractDate: new Date("2025-02-01"),
    fixedAssetsPlanItem: "ОС-002",
    isRegisteredInTreasury: true,
    contractNotes: "",
    parentContractId: 1,
    contractTerms: "100% после выполнения работ",
    plannedDeliveryDate: new Date("2025-08-15"),
    procurementMethodDetailId: 2,
    contractStatus: contractStatus.ACCEPTED,
    buyerId: 2,
    buyer: {
      id: 2,
      fullName: "ОсОО БишкекСтрой",
      shortName: "БС",
      isActive: true,
    },
    quarterDistribution: [],
  },
  {
    id: 3,
    contractNumber: "PC-2025-003",
    contractSum: 3500000,
    supplierId: "103",
    constructionType: "Капитальный ремонт",
    contractDate: new Date("2025-02-18"),
    fixedAssetsPlanItem: "ОС-003",
    isRegisteredInTreasury: false,
    contractNotes: "На согласовании",
    parentContractId: null,
    contractTerms: "30 дней отсрочки",
    plannedDeliveryDate: new Date("2025-09-01"),
    procurementMethodDetailId: 1,
    contractStatus: contractStatus.CANCELLED,
    buyerId: 3,
    buyer: {
      id: 3,
      fullName: "ЗАО ЭнергоСервис",
      shortName: "ЭС",
      isActive: true,
    },
    quarterDistribution: [],
  },
  {
    id: 4,
    contractNumber: "PC-2025-004",
    contractSum: 21500000,
    supplierId: "104",
    constructionType: "Новое строительство",
    contractDate: new Date("2025-03-05"),
    fixedAssetsPlanItem: "ОС-004",
    isRegisteredInTreasury: true,
    contractNotes: "Приоритетный объект",
    parentContractId: null,
    contractTerms: "20% аванс, остальное по этапам",
    plannedDeliveryDate: new Date("2025-12-20"),
    procurementMethodDetailId: 3,
    contractStatus: contractStatus.ACCEPTED,
    buyerId: 1,
    buyer: {
      id: 1,
      fullName: "АО Кыргызнефтегаз",
      shortName: "КНГ",
      isActive: true,
    },
    quarterDistribution: [],
  },
  {
    id: 5,
    contractNumber: "PC-2025-005",
    contractSum: 6400000,
    supplierId: "105",
    constructionType: "Модернизация",
    contractDate: new Date("2025-03-20"),
    fixedAssetsPlanItem: "ОС-005",
    isRegisteredInTreasury: false,
    contractNotes: "",
    parentContractId: 2,
    contractTerms: "По факту поставки",
    plannedDeliveryDate: new Date("2025-07-15"),
    procurementMethodDetailId: 2,
    contractStatus: contractStatus.CANCELLED,
    buyerId: 4,
    buyer: {
      id: 4,
      fullName: "ОсОО ТехИнвест",
      shortName: "ТИ",
      isActive: true,
    },
    quarterDistribution: [],
  },
  {
    id: 6,
    contractNumber: "PC-2025-006",
    contractSum: 9800000,
    supplierId: "106",
    constructionType: "Реконструкция",
    contractDate: new Date("2025-04-02"),
    fixedAssetsPlanItem: "ОС-006",
    isRegisteredInTreasury: true,
    contractNotes: "Дополнительное соглашение",
    parentContractId: 4,
    contractTerms: "50% / 50%",
    plannedDeliveryDate: new Date("2025-10-10"),
    procurementMethodDetailId: 4,
    contractStatus: contractStatus.ACCEPTED,
    buyerId: 2,
    buyer: {
      id: 2,
      fullName: "ОсОО БишкекСтрой",
      shortName: "БС",
      isActive: true,
    },
    quarterDistribution: [],
  },
  {
    id: 7,
    contractNumber: "PC-2025-007",
    contractSum: 15400000,
    supplierId: "107",
    constructionType: "Новое строительство",
    contractDate: new Date("2025-04-18"),
    fixedAssetsPlanItem: "ОС-007",
    isRegisteredInTreasury: true,
    contractNotes: "",
    parentContractId: null,
    contractTerms: "Поэтапная оплата",
    plannedDeliveryDate: new Date("2025-11-01"),
    procurementMethodDetailId: 1,
    contractStatus: contractStatus.ACCEPTED,
    buyerId: 5,
    buyer: {
      id: 5,
      fullName: "ОАО Водоканал",
      shortName: "ВК",
      isActive: true,
    },
    quarterDistribution: [],
  },
  {
    id: 8,
    contractNumber: "PC-2025-008",
    contractSum: 2800000,
    supplierId: "108",
    constructionType: "Капитальный ремонт",
    contractDate: new Date("2025-05-01"),
    fixedAssetsPlanItem: "ОС-008",
    isRegisteredInTreasury: false,
    contractNotes: "Требуется корректировка",
    parentContractId: null,
    contractTerms: "100% после приемки",
    plannedDeliveryDate: new Date("2025-06-25"),
    procurementMethodDetailId: 5,
    contractStatus: contractStatus.CANCELLED,
    buyerId: 3,
    buyer: {
      id: 3,
      fullName: "ЗАО ЭнергоСервис",
      shortName: "ЭС",
      isActive: true,
    },
    quarterDistribution: [],
  },
  {
    id: 9,
    contractNumber: "PC-2025-009",
    contractSum: 7200000,
    supplierId: "109",
    constructionType: "Модернизация",
    contractDate: new Date("2025-05-12"),
    fixedAssetsPlanItem: "ОС-009",
    isRegisteredInTreasury: true,
    contractNotes: "",
    parentContractId: 7,
    contractTerms: "40% аванс",
    plannedDeliveryDate: new Date("2025-09-30"),
    procurementMethodDetailId: 2,
    contractStatus: contractStatus.ACCEPTED,
    buyerId: 4,
    buyer: {
      id: 4,
      fullName: "ОсОО ТехИнвест",
      shortName: "ТИ",
      isActive: true,
    },
    quarterDistribution: [],
  },
  {
    id: 10,
    contractNumber: "PC-2025-010",
    contractSum: 18900000,
    supplierId: "110",
    constructionType: "Новое строительство",
    contractDate: new Date("2025-06-01"),
    fixedAssetsPlanItem: "ОС-010",
    isRegisteredInTreasury: true,
    contractNotes: "Крупный инфраструктурный проект",
    parentContractId: null,
    contractTerms: "По графику финансирования",
    plannedDeliveryDate: new Date("2026-02-15"),
    procurementMethodDetailId: 3,
    contractStatus: contractStatus.ACCEPTED,
    buyerId: 5,
    buyer: {
      id: 5,
      fullName: "ОАО Водоканал",
      shortName: "ВК",
      isActive: true,
    },
    quarterDistribution: [],
  },
];
