# Generated by Django 6.0.5 on 2026-06-02 15:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procurement', '0002_department_parent'),
    ]

    operations = [
        migrations.CreateModel(
            name='FunctionalCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code_api', models.CharField(db_index=True, max_length=64, unique=True, verbose_name="Код в формате API (например, '3 12 0 851')")),
                ('description', models.CharField(blank=True, max_length=255, null=True, verbose_name="Наименование объекта/цели (например, '03_12_00 § 851 (Витебск 3)')")),
                ('is_active', models.BooleanField(default=True, verbose_name='Действующий код')),
            ],
            options={
                'verbose_name': 'Код функциональной классификации',
                'verbose_name_plural': 'Справочник функциональных кодов',
                'ordering': ['code_api'],
            },
        ),
        migrations.CreateModel(
            name='ProgramCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code_api', models.CharField(db_index=True, max_length=32, unique=True, verbose_name="Код в формате API (например, '99 0')")),
                ('description', models.CharField(blank=True, max_length=255, null=True, verbose_name="Официальный вид (например, '99_00' или '19_01') и наименование")),
                ('is_active', models.BooleanField(default=True, verbose_name='Действующая программа')),
            ],
            options={
                'verbose_name': 'Код программной классификации',
                'verbose_name_plural': 'Справочник программных кодов',
                'ordering': ['code_api'],
            },
        ),
        migrations.RemoveField(
            model_name='budgetcosts',
            name='functional_code',
        ),
        migrations.RemoveField(
            model_name='budgetcosts',
            name='program_code',
        ),
        migrations.AddField(
            model_name='budgetcosts',
            name='functional_class',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='budget_costs', to='procurement.functionalcode', verbose_name='Функциональная классификация'),
        ),
        migrations.AddField(
            model_name='budgetcosts',
            name='program_class',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='budget_costs', to='procurement.programcode', verbose_name='Программная классификация'),
        ),
    ]
