# Generated by Django 6.0.5 on 2026-06-03 14:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procurement', '0007_okrbproduct_alter_supplier_unp_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UnitOfMeasurement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code_api', models.CharField(db_index=True, max_length=8, unique=True, verbose_name="Код в формате API (например, '0642')")),
                ('short_name', models.CharField(max_length=32, verbose_name="Краткое наименование (например, 'шт.', 'ед.')")),
                ('is_active', models.BooleanField(default=True, verbose_name='Актуальный код')),
            ],
            options={
                'verbose_name': 'Единица измерения (ОКРБ 008)',
                'verbose_name_plural': 'Справочник единиц измерения',
                'ordering': ['short_name'],
            },
        ),
        migrations.AlterField(
            model_name='planversion',
            name='val_type',
            field=models.CharField(db_index=True, max_length=8, verbose_name='Код ОКРБ 008 позиции ГПЗ на goszakupki.by'),
        ),
        migrations.AddField(
            model_name='planversion',
            name='val_unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='plan_versions', to='procurement.unitofmeasurement', verbose_name='Единица измерения'),
        ),
    ]
