# Generated by Django 6.0.5 on 2026-06-08 10:10

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procurement', '0010_buyer_alter_contract_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='contract_date',
            field=models.DateField(db_index=True, default=django.utils.timezone.now, verbose_name='Дата заключения договора'),
        ),
    ]
