# Generated by Django 6.0.5 on 2026-06-08 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procurement', '0011_alter_contract_contract_date'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='buyer',
            options={'ordering': ['shot_name'], 'verbose_name': 'Работник-закупщик', 'verbose_name_plural': 'Работники-закупщики'},
        ),
        migrations.AddField(
            model_name='buyer',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Действующий (не действующий) сотрудник'),
        ),
    ]
