# Generated by Django 6.0.5 on 2026-06-08 14:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procurement', '0012_alter_buyer_options_buyer_is_active'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contractitem',
            options={'ordering': ['-year', '-id'], 'verbose_name': 'Спецификация к договору', 'verbose_name_plural': 'Спецификация к договору'},
        ),
        migrations.AlterField(
            model_name='contractitem',
            name='plan_share',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='contract_items', to='procurement.planshare'),
        ),
        migrations.CreateModel(
            name='TreasuryPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_number', models.CharField(blank=True, help_text='Внутренний номер платежки из системы Клиент-ТК Минфина', max_length=32, null=True, verbose_name='Номер платежного поручения')),
                ('payment_date', models.DateField(db_index=True, verbose_name='Дата оплаты')),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Сумма оплаты')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='procurement.contract', verbose_name='Договор')),
            ],
            options={
                'verbose_name': 'Платежное поручение',
                'verbose_name_plural': 'Реестр фактических оплат (Платежки)',
                'ordering': ['-payment_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ContractQuarterlyFinance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quarter', models.CharField(choices=[('Q1', 'I Квартал'), ('Q2', 'II Квартал'), ('Q3', 'III Квартал'), ('Q4', 'IV Квартал')], db_index=True, max_length=2, verbose_name='Квартал')),
                ('year', models.PositiveIntegerField(db_index=True, verbose_name='Год')),
                ('planned_cost', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Прогнозируемый (планируемый) расход')),
                ('actual_cost', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Фактический расход (по платежным поручениям)')),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quarterly_finances', to='procurement.contract', verbose_name='Договор')),
            ],
            options={
                'verbose_name': 'Квартальное финансирование договора',
                'verbose_name_plural': 'Квартальное финансирование договоров',
                'ordering': ['year', 'quarter'],
                'constraints': [models.UniqueConstraint(fields=('contract', 'quarter', 'year'), name='unique_contract_quarter_per_year')],
            },
        ),
    ]
