/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  "/api/budget_costs/": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * @description Эндпоинт для пакетного импорта и распределения годового финансового обеспечения закупки.
     *     Принимает сырые коды казначейства и автоматически увязывает их с иерархией ЭКР ГКСЭ.
     */
    get: operations["budget_costs_list"];
    put?: never;
    /**
     * @description Кастомизированный метод POST.
     *     Поддерживает передачу как одной финансовой строки {}, так и массива [{}, {}].
     *     Исполняется строго в атомарной транзакции базы данных.
     */
    post: operations["budget_costs_create"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/budget_costs/{id}/": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * @description Эндпоинт для пакетного импорта и распределения годового финансового обеспечения закупки.
     *     Принимает сырые коды казначейства и автоматически увязывает их с иерархией ЭКР ГКСЭ.
     */
    get: operations["budget_costs_retrieve"];
    /**
     * @description Эндпоинт для пакетного импорта и распределения годового финансового обеспечения закупки.
     *     Принимает сырые коды казначейства и автоматически увязывает их с иерархией ЭКР ГКСЭ.
     */
    put: operations["budget_costs_update"];
    post?: never;
    /**
     * @description Эндпоинт для пакетного импорта и распределения годового финансового обеспечения закупки.
     *     Принимает сырые коды казначейства и автоматически увязывает их с иерархией ЭКР ГКСЭ.
     */
    delete: operations["budget_costs_destroy"];
    options?: never;
    head?: never;
    /**
     * @description Эндпоинт для пакетного импорта и распределения годового финансового обеспечения закупки.
     *     Принимает сырые коды казначейства и автоматически увязывает их с иерархией ЭКР ГКСЭ.
     */
    patch: operations["budget_costs_partial_update"];
    trace?: never;
  };
  "/api/buyers/": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** @description Эндпоинт вывода списка ответственных работников-закупщиков */
    get: operations["buyers_list"];
    put?: never;
    /** @description Эндпоинт вывода списка ответственных работников-закупщиков */
    post: operations["buyers_create"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/buyers/{id}/": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** @description Эндпоинт вывода списка ответственных работников-закупщиков */
    get: operations["buyers_retrieve"];
    /** @description Эндпоинт вывода списка ответственных работников-закупщиков */
    put: operations["buyers_update"];
    post?: never;
    /** @description Эндпоинт вывода списка ответственных работников-закупщиков */
    delete: operations["buyers_destroy"];
    options?: never;
    head?: never;
    /** @description Эндпоинт вывода списка ответственных работников-закупщиков */
    patch: operations["buyers_partial_update"];
    trace?: never;
  };
  "/api/contracts/": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** @description Эндпоинт управления и казначейского контроля реестра договоров ГКСЭ */
    get: operations["contracts_list"];
    put?: never;
    /** @description Эндпоинт управления и казначейского контроля реестра договоров ГКСЭ */
    post: operations["contracts_create"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/contracts/{id}/": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** @description Эндпоинт управления и казначейского контроля реестра договоров ГКСЭ */
    get: operations["contracts_retrieve"];
    /** @description Эндпоинт управления и казначейского контроля реестра договоров ГКСЭ */
    put: operations["contracts_update"];
    post?: never;
    /** @description Эндпоинт управления и казначейского контроля реестра договоров ГКСЭ */
    delete: operations["contracts_destroy"];
    options?: never;
    head?: never;
    /** @description Эндпоинт управления и казначейского контроля реестра договоров ГКСЭ */
    patch: operations["contracts_partial_update"];
    trace?: never;
  };
  "/api/departments/": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * @description Эндпоинт управления и вывода иерархического справочника подразделений ГКСЭ РБ.
     *     Поддерживает плоский вывод, сквозной текстовый поиск и древовидную сборку структуры.
     */
    get: operations["departments_list"];
    put?: never;
    /**
     * @description Эндпоинт управления и вывода иерархического справочника подразделений ГКСЭ РБ.
     *     Поддерживает плоский вывод, сквозной текстовый поиск и древовидную сборку структуры.
     */
    post: operations["departments_create"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/departments/{id}/": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * @description Эндпоинт управления и вывода иерархического справочника подразделений ГКСЭ РБ.
     *     Поддерживает плоский вывод, сквозной текстовый поиск и древовидную сборку структуры.
     */
    get: operations["departments_retrieve"];
    /**
     * @description Эндпоинт управления и вывода иерархического справочника подразделений ГКСЭ РБ.
     *     Поддерживает плоский вывод, сквозной текстовый поиск и древовидную сборку структуры.
     */
    put: operations["departments_update"];
    post?: never;
    /**
     * @description Эндпоинт управления и вывода иерархического справочника подразделений ГКСЭ РБ.
     *     Поддерживает плоский вывод, сквозной текстовый поиск и древовидную сборку структуры.
     */
    delete: operations["departments_destroy"];
    options?: never;
    head?: never;
    /**
     * @description Эндпоинт управления и вывода иерархического справочника подразделений ГКСЭ РБ.
     *     Поддерживает плоский вывод, сквозной текстовый поиск и древовидную сборку структуры.
     */
    patch: operations["departments_partial_update"];
    trace?: never;
  };
  "/api/goszakupki/pull-actual/": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** @description Синхронизация локальной СУБД с опубликованным на портале планом */
    get: operations["goszakupki_pull_actual_retrieve"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/goszakupki/push-draft/": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** @description Вызов отправки подготовленного проекта изменений на goszakupki.by */
    post: operations["goszakupki_push_draft_create"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/payments/": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** @description Эндпоинт для регистрации фактических оплат по договорам */
    get: operations["payments_list"];
    put?: never;
    /** @description Эндпоинт для регистрации фактических оплат по договорам */
    post: operations["payments_create"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/payments/{id}/": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** @description Эндпоинт для регистрации фактических оплат по договорам */
    get: operations["payments_retrieve"];
    /** @description Эндпоинт для регистрации фактических оплат по договорам */
    put: operations["payments_update"];
    post?: never;
    /** @description Эндпоинт для регистрации фактических оплат по договорам */
    delete: operations["payments_destroy"];
    options?: never;
    head?: never;
    /** @description Эндпоинт для регистрации фактических оплат по договорам */
    patch: operations["payments_partial_update"];
    trace?: never;
  };
  "/api/procurement_methods/": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** @description Эндпоинт вывода пунктов и статей процедур госзакупок РБ */
    get: operations["procurement_methods_list"];
    put?: never;
    /** @description Эндпоинт вывода пунктов и статей процедур госзакупок РБ */
    post: operations["procurement_methods_create"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/procurement_methods/{id}/": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** @description Эндпоинт вывода пунктов и статей процедур госзакупок РБ */
    get: operations["procurement_methods_retrieve"];
    /** @description Эндпоинт вывода пунктов и статей процедур госзакупок РБ */
    put: operations["procurement_methods_update"];
    post?: never;
    /** @description Эндпоинт вывода пунктов и статей процедур госзакупок РБ */
    delete: operations["procurement_methods_destroy"];
    options?: never;
    head?: never;
    /** @description Эндпоинт вывода пунктов и статей процедур госзакупок РБ */
    patch: operations["procurement_methods_partial_update"];
    trace?: never;
  };
  "/api/suppliers/": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** @description Эндпоинт управления ведомственным справочником контрагентов */
    get: operations["suppliers_list"];
    put?: never;
    /** @description Эндпоинт управления ведомственным справочником контрагентов */
    post: operations["suppliers_create"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/suppliers/{id}/": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** @description Эндпоинт управления ведомственным справочником контрагентов */
    get: operations["suppliers_retrieve"];
    /** @description Эндпоинт управления ведомственным справочником контрагентов */
    put: operations["suppliers_update"];
    post?: never;
    /** @description Эндпоинт управления ведомственным справочником контрагентов */
    delete: operations["suppliers_destroy"];
    options?: never;
    head?: never;
    /** @description Эндпоинт управления ведомственным справочником контрагентов */
    patch: operations["suppliers_partial_update"];
    trace?: never;
  };
  "/api/units_of_measurement/": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * @description Эндпоинт ведомственного справочника единиц измерения ОКРБ 008-95.
     *     Оптимизирован для быстрых выпадающих списков и автокомплитов на фронтенде.
     */
    get: operations["units_of_measurement_list"];
    put?: never;
    /**
     * @description Эндпоинт ведомственного справочника единиц измерения ОКРБ 008-95.
     *     Оптимизирован для быстрых выпадающих списков и автокомплитов на фронтенде.
     */
    post: operations["units_of_measurement_create"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/units_of_measurement/{id}/": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * @description Эндпоинт ведомственного справочника единиц измерения ОКРБ 008-95.
     *     Оптимизирован для быстрых выпадающих списков и автокомплитов на фронтенде.
     */
    get: operations["units_of_measurement_retrieve"];
    /**
     * @description Эндпоинт ведомственного справочника единиц измерения ОКРБ 008-95.
     *     Оптимизирован для быстрых выпадающих списков и автокомплитов на фронтенде.
     */
    put: operations["units_of_measurement_update"];
    post?: never;
    /**
     * @description Эндпоинт ведомственного справочника единиц измерения ОКРБ 008-95.
     *     Оптимизирован для быстрых выпадающих списков и автокомплитов на фронтенде.
     */
    delete: operations["units_of_measurement_destroy"];
    options?: never;
    head?: never;
    /**
     * @description Эндпоинт ведомственного справочника единиц измерения ОКРБ 008-95.
     *     Оптимизирован для быстрых выпадающих списков и автокомплитов на фронтенде.
     */
    patch: operations["units_of_measurement_partial_update"];
    trace?: never;
  };
}
export type webhooks = Record<string, never>;
export interface components {
  schemas: {
    /** @description Используется ТОЛЬКО для POST-запросов импорта 'сырых' данных извне */
    BudgetCostsImport: {
      /** Id позиции ГПЗ на goszakupki.by */
      purchases_items_id: number;
      /** Год финансирования из бюджета */
      year?: number;
      /**
       * Ориентировочная стоимость позиции ГПЗ
       * Format: decimal
       */
      cost?: string;
      functional_code?: string;
      program_code?: string;
      economic_code?: string;
      /** Код бюджета позиции плана */
      budget_code?: number;
      /** Описание кода бюджета */
      budget_code_name?: string;
      /** Код ведомственной классификации */
      department_code?: string | null;
      /** УНК заказчика позиции */
      unk?: string | null;
      /** Код территориального казначейства */
      tk_id?: number | null;
      /** Экономический код расходов (ЭКР) */
      economic_class: number;
    };
    /** @description Сериализатор для справочника работников-закупщиков ГКСЭ */
    Buyer: {
      readonly id: number;
      /** Фамилия и инициалы */
      shot_name: string;
      /** ФИО полностью */
      full_name: string;
      /** Действующий (не действующий) сотрудник */
      is_active?: boolean;
    };
    /** @description Единый зарегистрированный договор ГКСЭ (Шапка + Аналитика) */
    Contract: {
      readonly id: number;
      /** Номер договора */
      number: string;
      /**
       * Дата заключения договора
       * Format: date
       */
      contract_date?: string;
      /** Исполнитель/Поставщик */
      supplier: number;
      readonly supplier_detail: components["schemas"]["Supplier"];
      /**
       * Общая сумма договора
       * Format: decimal
       */
      total_cost: string;
      /** Закупщик */
      buyer?: number | null;
      /** Основной договор (для Доп. соглашений) */
      parent_contract?: number | null;
      /** Регистрация в территориальном казначействе */
      is_registered_in_treasury?: boolean;
      /** Условия оплаты */
      payment_terms?: string | null;
      /**
       * Плановая дата поставки / выполнения работ / оказания услуг
       * Format: date
       */
      planned_delivery_date: string;
      /** Примечание / Дополнительная информация */
      notice?: string | null;
      /** Пункт перечня плана основных средств */
      fixed_assets_plan_item?: string | null;
      /**
       * Вид процедуры закупки (Пункт)
       * @description Выбор конкретного пункта процедуры из ведомственного справочника РБ
       */
      procurement_method_detail?: number | null;
      readonly procurement_method_detail_info: components["schemas"]["ProcurementMethodDetail"];
      /** Вид строительных работ / Объект строительства */
      construction_type?: string | null;
      /** Format: date-time */
      readonly created_at: string;
      readonly items: components["schemas"]["ContractItem"][];
      readonly payments: components["schemas"]["TreasuryPayment"][];
      readonly days_remaining: number;
      readonly is_urgent_warning: boolean;
      /** @description Интегрирует расчет поквартального прогноза (как в примере с картриджами) в JSON */
      readonly quarterly_analytics: {
        [key: string]: unknown;
      };
    };
    /** @description Спецификация договора (Детализация списания лимитов подразделений) */
    ContractItem: {
      readonly id: number;
      contract: number;
      plan_share: number;
      /**
       * Количество по договору
       * Format: decimal
       */
      contract_amount: string;
      /**
       * Сумма по договору
       * Format: decimal
       */
      contract_cost: string;
    };
    /** @description Рекурсивный сериализатор для автоматической сборки дерева подразделений ГКСЭ */
    DepartmentTree: {
      readonly id: number;
      /** Полное наименование подразделения */
      full_name: string;
      /** Краткое наименование подразделения */
      short_name: string;
      /** Действующее подразделение */
      is_active?: boolean;
      readonly is_root: boolean;
      readonly sub_departments: string;
    };
    PaginatedBudgetCostsImportList: {
      /** @example 123 */
      count: number;
      /**
       * Format: uri
       * @example http://api.example.org/accounts/?offset=400&limit=100
       */
      next?: string | null;
      /**
       * Format: uri
       * @example http://api.example.org/accounts/?offset=200&limit=100
       */
      previous?: string | null;
      results: components["schemas"]["BudgetCostsImport"][];
    };
    PaginatedContractList: {
      /** @example 123 */
      count: number;
      /**
       * Format: uri
       * @example http://api.example.org/accounts/?offset=400&limit=100
       */
      next?: string | null;
      /**
       * Format: uri
       * @example http://api.example.org/accounts/?offset=200&limit=100
       */
      previous?: string | null;
      results: components["schemas"]["Contract"][];
    };
    /** @description Используется ТОЛЬКО для POST-запросов импорта 'сырых' данных извне */
    PatchedBudgetCostsImport: {
      /** Id позиции ГПЗ на goszakupki.by */
      purchases_items_id?: number;
      /** Год финансирования из бюджета */
      year?: number;
      /**
       * Ориентировочная стоимость позиции ГПЗ
       * Format: decimal
       */
      cost?: string;
      functional_code?: string;
      program_code?: string;
      economic_code?: string;
      /** Код бюджета позиции плана */
      budget_code?: number;
      /** Описание кода бюджета */
      budget_code_name?: string;
      /** Код ведомственной классификации */
      department_code?: string | null;
      /** УНК заказчика позиции */
      unk?: string | null;
      /** Код территориального казначейства */
      tk_id?: number | null;
      /** Экономический код расходов (ЭКР) */
      economic_class?: number;
    };
    /** @description Сериализатор для справочника работников-закупщиков ГКСЭ */
    PatchedBuyer: {
      readonly id?: number;
      /** Фамилия и инициалы */
      shot_name?: string;
      /** ФИО полностью */
      full_name?: string;
      /** Действующий (не действующий) сотрудник */
      is_active?: boolean;
    };
    /** @description Единый зарегистрированный договор ГКСЭ (Шапка + Аналитика) */
    PatchedContract: {
      readonly id?: number;
      /** Номер договора */
      number?: string;
      /**
       * Дата заключения договора
       * Format: date
       */
      contract_date?: string;
      /** Исполнитель/Поставщик */
      supplier?: number;
      readonly supplier_detail?: components["schemas"]["Supplier"];
      /**
       * Общая сумма договора
       * Format: decimal
       */
      total_cost?: string;
      /** Закупщик */
      buyer?: number | null;
      /** Основной договор (для Доп. соглашений) */
      parent_contract?: number | null;
      /** Регистрация в территориальном казначействе */
      is_registered_in_treasury?: boolean;
      /** Условия оплаты */
      payment_terms?: string | null;
      /**
       * Плановая дата поставки / выполнения работ / оказания услуг
       * Format: date
       */
      planned_delivery_date?: string;
      /** Примечание / Дополнительная информация */
      notice?: string | null;
      /** Пункт перечня плана основных средств */
      fixed_assets_plan_item?: string | null;
      /**
       * Вид процедуры закупки (Пункт)
       * @description Выбор конкретного пункта процедуры из ведомственного справочника РБ
       */
      procurement_method_detail?: number | null;
      readonly procurement_method_detail_info?: components["schemas"]["ProcurementMethodDetail"];
      /** Вид строительных работ / Объект строительства */
      construction_type?: string | null;
      /** Format: date-time */
      readonly created_at?: string;
      readonly items?: components["schemas"]["ContractItem"][];
      readonly payments?: components["schemas"]["TreasuryPayment"][];
      readonly days_remaining?: number;
      readonly is_urgent_warning?: boolean;
      /** @description Интегрирует расчет поквартального прогноза (как в примере с картриджами) в JSON */
      readonly quarterly_analytics?: {
        [key: string]: unknown;
      };
    };
    /** @description Рекурсивный сериализатор для автоматической сборки дерева подразделений ГКСЭ */
    PatchedDepartmentTree: {
      readonly id?: number;
      /** Полное наименование подразделения */
      full_name?: string;
      /** Краткое наименование подразделения */
      short_name?: string;
      /** Действующее подразделение */
      is_active?: boolean;
      readonly is_root?: boolean;
      readonly sub_departments?: string;
    };
    /** @description Сериализатор иерархических пунктов процедур закупок РБ */
    PatchedProcurementMethodDetail: {
      readonly id?: number;
      /**
       * Наименование процедуры / пункта
       * @description Например: 'ОИ по пункту 26 (Коммунальные услуги)' или 'Электронный аукцион'
       */
      name?: string;
      /**
       * Родительский метод закупки
       * @description Оставьте пустым, если это верхнеуровневый метод (например, просто 'Закупка из одного источника')
       */
      parent?: number | null;
      /** Актуальный метод */
      is_active?: boolean;
    };
    /** @description Сериализатор контрагентов (ЕАЭС: УНП/ИНН) */
    PatchedSupplier: {
      readonly id?: number;
      /** Наименование организации */
      name?: string;
      /** УНП */
      unp?: string;
    };
    /** @description Обновленный сериализатор единиц измерения под актуальную модель */
    PatchedUnitOfMeasurement: {
      readonly id?: number;
      /** Код в формате API (например, '0642') */
      code?: string;
      /** Краткое наименование (например, 'шт.', 'ед.') */
      short_name?: string;
      /** Актуальный код */
      is_active?: boolean;
    };
    /** @description Сериализатор иерархических пунктов процедур закупок РБ */
    ProcurementMethodDetail: {
      readonly id: number;
      /**
       * Наименование процедуры / пункта
       * @description Например: 'ОИ по пункту 26 (Коммунальные услуги)' или 'Электронный аукцион'
       */
      name: string;
      /**
       * Родительский метод закупки
       * @description Оставьте пустым, если это верхнеуровневый метод (например, просто 'Закупка из одного источника')
       */
      parent?: number | null;
      /** Актуальный метод */
      is_active?: boolean;
    };
    /** @description Сериализатор контрагентов (ЕАЭС: УНП/ИНН) */
    Supplier: {
      readonly id: number;
      /** Наименование организации */
      name: string;
      /** УНП */
      unp: string;
    };
    /** @description Сериализатор платежных поручений (Фактические кассовые оплаты) */
    TreasuryPayment: {
      readonly id: number;
      /** Договор */
      contract: number;
      /**
       * Номер платежного поручения
       * @description Внутренний номер платежки из системы Клиент-ТК Минфина
       */
      payment_number?: string | null;
      /**
       * Дата оплаты
       * Format: date
       */
      payment_date?: string;
      /**
       * Сумма оплаты
       * Format: decimal
       */
      amount?: string;
      /** Format: date-time */
      readonly created_at: string;
    };
    /** @description Обновленный сериализатор единиц измерения под актуальную модель */
    UnitOfMeasurement: {
      readonly id: number;
      /** Код в формате API (например, '0642') */
      code: string;
      /** Краткое наименование (например, 'шт.', 'ед.') */
      short_name: string;
      /** Актуальный код */
      is_active?: boolean;
    };
  };
  responses: never;
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
  budget_costs_list: {
    parameters: {
      query?: {
        budget_code?: number;
        /** @description Number of results to return per page. */
        limit?: number;
        /** @description The initial index from which to return the results. */
        offset?: number;
        purchases_items_id?: number;
        year?: number;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["PaginatedBudgetCostsImportList"];
        };
      };
    };
  };
  budget_costs_create: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["BudgetCostsImport"];
        "application/x-www-form-urlencoded": components["schemas"]["BudgetCostsImport"];
        "multipart/form-data": components["schemas"]["BudgetCostsImport"];
      };
    };
    responses: {
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["BudgetCostsImport"];
        };
      };
    };
  };
  budget_costs_retrieve: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        /** @description A unique integer value identifying this Бюджетное финансирование. */
        id: number;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["BudgetCostsImport"];
        };
      };
    };
  };
  budget_costs_update: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        /** @description A unique integer value identifying this Бюджетное финансирование. */
        id: number;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["BudgetCostsImport"];
        "application/x-www-form-urlencoded": components["schemas"]["BudgetCostsImport"];
        "multipart/form-data": components["schemas"]["BudgetCostsImport"];
      };
    };
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["BudgetCostsImport"];
        };
      };
    };
  };
  budget_costs_destroy: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        /** @description A unique integer value identifying this Бюджетное финансирование. */
        id: number;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description No response body */
      204: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  budget_costs_partial_update: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        /** @description A unique integer value identifying this Бюджетное финансирование. */
        id: number;
      };
      cookie?: never;
    };
    requestBody?: {
      content: {
        "application/json": components["schemas"]["PatchedBudgetCostsImport"];
        "application/x-www-form-urlencoded": components["schemas"]["PatchedBudgetCostsImport"];
        "multipart/form-data": components["schemas"]["PatchedBudgetCostsImport"];
      };
    };
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["BudgetCostsImport"];
        };
      };
    };
  };
  buyers_list: {
    parameters: {
      query?: {
        /** @description A search term. */
        search?: string;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Buyer"][];
        };
      };
    };
  };
  buyers_create: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["Buyer"];
        "application/x-www-form-urlencoded": components["schemas"]["Buyer"];
        "multipart/form-data": components["schemas"]["Buyer"];
      };
    };
    responses: {
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Buyer"];
        };
      };
    };
  };
  buyers_retrieve: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        /** @description A unique integer value identifying this Работник-закупщик. */
        id: number;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Buyer"];
        };
      };
    };
  };
  buyers_update: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        /** @description A unique integer value identifying this Работник-закупщик. */
        id: number;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["Buyer"];
        "application/x-www-form-urlencoded": components["schemas"]["Buyer"];
        "multipart/form-data": components["schemas"]["Buyer"];
      };
    };
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Buyer"];
        };
      };
    };
  };
  buyers_destroy: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        /** @description A unique integer value identifying this Работник-закупщик. */
        id: number;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description No response body */
      204: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  buyers_partial_update: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        /** @description A unique integer value identifying this Работник-закупщик. */
        id: number;
      };
      cookie?: never;
    };
    requestBody?: {
      content: {
        "application/json": components["schemas"]["PatchedBuyer"];
        "application/x-www-form-urlencoded": components["schemas"]["PatchedBuyer"];
        "multipart/form-data": components["schemas"]["PatchedBuyer"];
      };
    };
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Buyer"];
        };
      };
    };
  };
  contracts_list: {
    parameters: {
      query?: {
        /** @description Number of results to return per page. */
        limit?: number;
        /** @description The initial index from which to return the results. */
        offset?: number;
        supplier?: number;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["PaginatedContractList"];
        };
      };
    };
  };
  contracts_create: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["Contract"];
        "application/x-www-form-urlencoded": components["schemas"]["Contract"];
        "multipart/form-data": components["schemas"]["Contract"];
      };
    };
    responses: {
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Contract"];
        };
      };
    };
  };
  contracts_retrieve: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        /** @description A unique integer value identifying this Договор. */
        id: number;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Contract"];
        };
      };
    };
  };
  contracts_update: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        /** @description A unique integer value identifying this Договор. */
        id: number;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["Contract"];
        "application/x-www-form-urlencoded": components["schemas"]["Contract"];
        "multipart/form-data": components["schemas"]["Contract"];
      };
    };
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Contract"];
        };
      };
    };
  };
  contracts_destroy: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        /** @description A unique integer value identifying this Договор. */
        id: number;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description No response body */
      204: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  contracts_partial_update: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        /** @description A unique integer value identifying this Договор. */
        id: number;
      };
      cookie?: never;
    };
    requestBody?: {
      content: {
        "application/json": components["schemas"]["PatchedContract"];
        "application/x-www-form-urlencoded": components["schemas"]["PatchedContract"];
        "multipart/form-data": components["schemas"]["PatchedContract"];
      };
    };
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Contract"];
        };
      };
    };
  };
  departments_list: {
    parameters: {
      query?: {
        is_active?: boolean;
        parent?: number;
        /** @description A search term. */
        search?: string;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["DepartmentTree"][];
        };
      };
    };
  };
  departments_create: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["DepartmentTree"];
        "application/x-www-form-urlencoded": components["schemas"]["DepartmentTree"];
        "multipart/form-data": components["schemas"]["DepartmentTree"];
      };
    };
    responses: {
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["DepartmentTree"];
        };
      };
    };
  };
  departments_retrieve: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        /** @description A unique integer value identifying this Подразделение. */
        id: number;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["DepartmentTree"];
        };
      };
    };
  };
  departments_update: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        /** @description A unique integer value identifying this Подразделение. */
        id: number;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["DepartmentTree"];
        "application/x-www-form-urlencoded": components["schemas"]["DepartmentTree"];
        "multipart/form-data": components["schemas"]["DepartmentTree"];
      };
    };
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["DepartmentTree"];
        };
      };
    };
  };
  departments_destroy: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        /** @description A unique integer value identifying this Подразделение. */
        id: number;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description No response body */
      204: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  departments_partial_update: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        /** @description A unique integer value identifying this Подразделение. */
        id: number;
      };
      cookie?: never;
    };
    requestBody?: {
      content: {
        "application/json": components["schemas"]["PatchedDepartmentTree"];
        "application/x-www-form-urlencoded": components["schemas"]["PatchedDepartmentTree"];
        "multipart/form-data": components["schemas"]["PatchedDepartmentTree"];
      };
    };
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["DepartmentTree"];
        };
      };
    };
  };
  goszakupki_pull_actual_retrieve: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description No response body */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  goszakupki_push_draft_create: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description No response body */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  payments_list: {
    parameters: {
      query?: {
        contract?: number;
        /** @description Number of results to return per page. */
        limit?: number;
        /** @description The initial index from which to return the results. */
        offset?: number;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["PaginatedBudgetCostsImportList"];
        };
      };
    };
  };
  payments_create: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["BudgetCostsImport"];
        "application/x-www-form-urlencoded": components["schemas"]["BudgetCostsImport"];
        "multipart/form-data": components["schemas"]["BudgetCostsImport"];
      };
    };
    responses: {
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["BudgetCostsImport"];
        };
      };
    };
  };
  payments_retrieve: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        /** @description A unique integer value identifying this Платежное поручение. */
        id: number;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["BudgetCostsImport"];
        };
      };
    };
  };
  payments_update: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        /** @description A unique integer value identifying this Платежное поручение. */
        id: number;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["BudgetCostsImport"];
        "application/x-www-form-urlencoded": components["schemas"]["BudgetCostsImport"];
        "multipart/form-data": components["schemas"]["BudgetCostsImport"];
      };
    };
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["BudgetCostsImport"];
        };
      };
    };
  };
  payments_destroy: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        /** @description A unique integer value identifying this Платежное поручение. */
        id: number;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description No response body */
      204: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  payments_partial_update: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        /** @description A unique integer value identifying this Платежное поручение. */
        id: number;
      };
      cookie?: never;
    };
    requestBody?: {
      content: {
        "application/json": components["schemas"]["PatchedBudgetCostsImport"];
        "application/x-www-form-urlencoded": components["schemas"]["PatchedBudgetCostsImport"];
        "multipart/form-data": components["schemas"]["PatchedBudgetCostsImport"];
      };
    };
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["BudgetCostsImport"];
        };
      };
    };
  };
  procurement_methods_list: {
    parameters: {
      query?: {
        parent?: number;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ProcurementMethodDetail"][];
        };
      };
    };
  };
  procurement_methods_create: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["ProcurementMethodDetail"];
        "application/x-www-form-urlencoded": components["schemas"]["ProcurementMethodDetail"];
        "multipart/form-data": components["schemas"]["ProcurementMethodDetail"];
      };
    };
    responses: {
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ProcurementMethodDetail"];
        };
      };
    };
  };
  procurement_methods_retrieve: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        /** @description A unique integer value identifying this Детализация процедуры закупки. */
        id: number;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ProcurementMethodDetail"];
        };
      };
    };
  };
  procurement_methods_update: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        /** @description A unique integer value identifying this Детализация процедуры закупки. */
        id: number;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["ProcurementMethodDetail"];
        "application/x-www-form-urlencoded": components["schemas"]["ProcurementMethodDetail"];
        "multipart/form-data": components["schemas"]["ProcurementMethodDetail"];
      };
    };
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ProcurementMethodDetail"];
        };
      };
    };
  };
  procurement_methods_destroy: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        /** @description A unique integer value identifying this Детализация процедуры закупки. */
        id: number;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description No response body */
      204: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  procurement_methods_partial_update: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        /** @description A unique integer value identifying this Детализация процедуры закупки. */
        id: number;
      };
      cookie?: never;
    };
    requestBody?: {
      content: {
        "application/json": components["schemas"]["PatchedProcurementMethodDetail"];
        "application/x-www-form-urlencoded": components["schemas"]["PatchedProcurementMethodDetail"];
        "multipart/form-data": components["schemas"]["PatchedProcurementMethodDetail"];
      };
    };
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ProcurementMethodDetail"];
        };
      };
    };
  };
  suppliers_list: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Supplier"][];
        };
      };
    };
  };
  suppliers_create: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["Supplier"];
        "application/x-www-form-urlencoded": components["schemas"]["Supplier"];
        "multipart/form-data": components["schemas"]["Supplier"];
      };
    };
    responses: {
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Supplier"];
        };
      };
    };
  };
  suppliers_retrieve: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        /** @description A unique integer value identifying this Поставщик. */
        id: number;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Supplier"];
        };
      };
    };
  };
  suppliers_update: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        /** @description A unique integer value identifying this Поставщик. */
        id: number;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["Supplier"];
        "application/x-www-form-urlencoded": components["schemas"]["Supplier"];
        "multipart/form-data": components["schemas"]["Supplier"];
      };
    };
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Supplier"];
        };
      };
    };
  };
  suppliers_destroy: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        /** @description A unique integer value identifying this Поставщик. */
        id: number;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description No response body */
      204: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  suppliers_partial_update: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        /** @description A unique integer value identifying this Поставщик. */
        id: number;
      };
      cookie?: never;
    };
    requestBody?: {
      content: {
        "application/json": components["schemas"]["PatchedSupplier"];
        "application/x-www-form-urlencoded": components["schemas"]["PatchedSupplier"];
        "multipart/form-data": components["schemas"]["PatchedSupplier"];
      };
    };
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Supplier"];
        };
      };
    };
  };
  units_of_measurement_list: {
    parameters: {
      query?: {
        code?: string;
        /** @description A search term. */
        search?: string;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["UnitOfMeasurement"][];
        };
      };
    };
  };
  units_of_measurement_create: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["UnitOfMeasurement"];
        "application/x-www-form-urlencoded": components["schemas"]["UnitOfMeasurement"];
        "multipart/form-data": components["schemas"]["UnitOfMeasurement"];
      };
    };
    responses: {
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["UnitOfMeasurement"];
        };
      };
    };
  };
  units_of_measurement_retrieve: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        /** @description A unique integer value identifying this Единица измерения (ОКРБ 008). */
        id: number;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["UnitOfMeasurement"];
        };
      };
    };
  };
  units_of_measurement_update: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        /** @description A unique integer value identifying this Единица измерения (ОКРБ 008). */
        id: number;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["UnitOfMeasurement"];
        "application/x-www-form-urlencoded": components["schemas"]["UnitOfMeasurement"];
        "multipart/form-data": components["schemas"]["UnitOfMeasurement"];
      };
    };
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["UnitOfMeasurement"];
        };
      };
    };
  };
  units_of_measurement_destroy: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        /** @description A unique integer value identifying this Единица измерения (ОКРБ 008). */
        id: number;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description No response body */
      204: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  units_of_measurement_partial_update: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        /** @description A unique integer value identifying this Единица измерения (ОКРБ 008). */
        id: number;
      };
      cookie?: never;
    };
    requestBody?: {
      content: {
        "application/json": components["schemas"]["PatchedUnitOfMeasurement"];
        "application/x-www-form-urlencoded": components["schemas"]["PatchedUnitOfMeasurement"];
        "multipart/form-data": components["schemas"]["PatchedUnitOfMeasurement"];
      };
    };
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["UnitOfMeasurement"];
        };
      };
    };
  };
}
