upstream frontend {
    # Используем имя сервиса React из docker-compose
    server frontend:5173;
}

upstream backend {
    # Используем имя сервиса Django из docker-compose
    server backend:8000;
}

server {
    listen 80;

    client_max_body_size 100M; # Укажите нужный вам лимит (например, 20 Мегабайт)

    # Обслуживание статических файлов из указанного пути
    location /staticfiles/ {
        # Путь внутри контейнера Nginx, куда будет примонтирована папка /backend/static
        alias /var/www/static/;
    }

    # Обслуживание медиа-файлов из указанного пути
    location /media/ {
        # Путь внутри контейнера Nginx, куда будет примонтирована папка /backend/media
        alias /var/www/media/;
    }

        # Объединенная группа для Django (API, логин, админка)
    location ~ ^/(api|admin|login|logout)/ {
        proxy_pass http://backend;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_set_header Host $http_host;

        # Настройка для CSRF и сессий
        proxy_cookie_path / '/; SameSite=Lax';
        # Strict может иногда мешать редиректам
    }

    # Все остальные запросы направляем на React-приложение
    location / {
        proxy_pass http://frontend;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    }
}



