# Generated by Django 6.0.5 on 2026-06-19 18:23

import django.db.models.deletion
from django.db import migrations, models
import procurement.services.get_current_datetime



class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Buyer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shot_name', models.CharField(db_index=True, max_length=64, unique=True, verbose_name='Фамилия и инициалы')),
                ('full_name', models.CharField(db_index=True, max_length=128, unique=True, verbose_name='ФИО полностью')),
                ('is_active', models.BooleanField(default=True, verbose_name='Действующий (не действующий) сотрудник')),
            ],
            options={
                'verbose_name': 'Работник-закупщик',
                'verbose_name_plural': 'Работники-закупщики',
                'ordering': ['shot_name'],
            },
        ),
        migrations.CreateModel(
            name='ExternalEconomicCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code_api', models.CharField(db_index=True, max_length=64, unique=True, verbose_name="Код в формате API (например, '1 10 10 99')")),
                ('description', models.TextField(verbose_name="Наименование статьи (например, '1.10.06.00 Оплата услуг связи')")),
                ('is_active', models.BooleanField(default=True, verbose_name='Действующий код')),
            ],
            options={
                'verbose_name': 'Внешний код ЭКР',
                'verbose_name_plural': 'Справочник внешних кодов ЭКР',
                'ordering': ['code_api'],
            },
        ),
        migrations.CreateModel(
            name='FunctionalCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code_api', models.CharField(db_index=True, max_length=64, unique=True, verbose_name="Код в формате API (например, '3 12 0 851')")),
                ('description', models.CharField(blank=True, max_length=255, null=True, verbose_name="Наименование объекта/цели (например, '03_12_00 § 851 (Витебск 3)')")),
                ('is_active', models.BooleanField(default=True, verbose_name='Действующий код')),
            ],
            options={
                'verbose_name': 'Код функциональной классификации',
                'verbose_name_plural': 'Справочник функциональных кодов',
                'ordering': ['code_api'],
            },
        ),
        migrations.CreateModel(
            name='OkrbProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(db_index=True, max_length=32, unique=True, verbose_name='Код ОКРБ 007 (например, 62.01.11.900)')),
                ('title', models.TextField(verbose_name='Наименование группировки/вида продукции')),
                ('is_active', models.BooleanField(default=True, verbose_name='Актуальный код')),
            ],
            options={
                'verbose_name': 'Код ОКРБ 007',
                'verbose_name_plural': 'Справочник ОКРБ 007',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num', models.CharField(blank=True, db_index=True, max_length=64, null=True, verbose_name='Регистрационный номер позиции ГПЗ на goszakupki.by')),
                ('is_public', models.BooleanField(db_index=True, default=True, verbose_name='Публикуется на goszakupki.by')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='Активная или удаленная позиция')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Пункт плана закупки (мастер-запись)',
                'verbose_name_plural': 'Пункты плана закупок (мастер-записи)',
            },
        ),
        migrations.CreateModel(
            name='ProgramCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code_api', models.CharField(db_index=True, max_length=32, unique=True, verbose_name="Код в формате API (например, '99 0')")),
                ('description', models.CharField(blank=True, max_length=255, null=True, verbose_name="Официальный вид (например, '99_00' или '19_01') и наименование")),
                ('is_active', models.BooleanField(default=True, verbose_name='Действующая программа')),
            ],
            options={
                'verbose_name': 'Код программной классификации',
                'verbose_name_plural': 'Справочник программных кодов',
                'ordering': ['code_api'],
            },
        ),
        migrations.CreateModel(
            name='Purchases',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purchase_id', models.PositiveIntegerField(blank=True, null=True, verbose_name='ID плана')),
                ('purchase_num', models.CharField(blank=True, db_index=True, max_length=32, null=True, verbose_name='Регистрационный номер плана ГПЗ на goszakupki.by')),
                ('company', models.CharField(default='Центральный аппарат Государственного комитета судебных экспертиз Республики Беларусь', verbose_name='Наименование организации')),
                ('ved', models.CharField(default='Государственный комитет судебных экспертиз Республики Беларусь', verbose_name='Ведомственная принадлежность')),
                ('country', models.CharField(default='Республика Беларусь', verbose_name='Страна организации')),
                ('region', models.CharField(blank=True, null=True, verbose_name='Область (регион) организации')),
                ('city', models.CharField(blank=True, null=True, verbose_name='Город (населенный пункт) организации')),
                ('address', models.CharField(blank=True, null=True, verbose_name='Адрес организации')),
                ('establishment', models.PositiveIntegerField(blank=True, null=True, verbose_name='Идентификатор ведомства, к которому относится организация')),
                ('date_added', models.DateTimeField(blank=True, null=True, verbose_name='Время добавления плана')),
                ('date_edit', models.DateTimeField(blank=True, null=True, verbose_name='Время редактирования плана')),
                ('date_sign', models.DateTimeField(blank=True, null=True, verbose_name='Дата утверждения плана')),
                ('signer_descrip', models.CharField(default='Алешкевич Алексей Степанович', verbose_name='Лицо утвердившее план')),
                ('sender_descrip', models.CharField(default='Гладкая Ольга Николаевна', verbose_name='Лицо разместившее план')),
                ('year', models.PositiveIntegerField(blank=True, null=True, verbose_name='Год плана')),
                ('is_draft', models.PositiveIntegerField(default=1, verbose_name='Признак черновика плана')),
                ('at_updated', models.CharField(blank=True, null=True, verbose_name='Метка времени последнего обновления плана закупок')),
            ],
            options={
                'verbose_name': 'План закупок ГКСЭ',
                'verbose_name_plural': 'Планы закупок ГКСЭ',
                'ordering': ['-year'],
            },
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=512, verbose_name='Наименование организации')),
                ('unp', models.CharField(db_index=True, max_length=16, unique=True, verbose_name='УНП')),
            ],
            options={
                'verbose_name': 'Поставщик',
                'verbose_name_plural': 'Справочник поставщиков',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='UnitOfMeasurement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(db_index=True, max_length=8, unique=True, verbose_name="Код в формате API (например, '0642')")),
                ('short_name', models.CharField(max_length=32, verbose_name="Краткое наименование (например, 'шт.', 'ед.')")),
                ('is_active', models.BooleanField(default=True, verbose_name='Актуальный код')),
            ],
            options={
                'verbose_name': 'Единица измерения (ОКРБ 008)',
                'verbose_name_plural': 'Справочник единиц измерения',
                'ordering': ['short_name'],
            },
        ),
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=64, verbose_name='Номер договора')),
                ('contract_date', models.DateField(db_index=True, default=procurement.services.get_current_date(), verbose_name='Дата заключения договора')),
                ('total_cost', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Общая сумма договора')),
                ('is_registered_in_treasury', models.BooleanField(db_index=True, default=False, verbose_name='Регистрация в территориальном казначействе')),
                ('payment_terms', models.CharField(blank=True, max_length=2048, null=True, verbose_name='Условия оплаты')),
                ('planned_delivery_date', models.DateField(db_index=True, verbose_name='Плановая дата поставки / выполнения работ / оказания услуг')),
                ('notice', models.TextField(blank=True, null=True, verbose_name='Примечание / Дополнительная информация')),
                ('fixed_assets_plan_item', models.CharField(blank=True, max_length=255, null=True, verbose_name='Пункт перечня плана основных средств')),
                ('construction_type', models.CharField(blank=True, max_length=2048, null=True, verbose_name='Вид строительных работ / Объект строительства')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('buyer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='buyer_contracts', to='procurement.buyer', verbose_name='Закупщик')),
                ('parent_contract', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='main_agreements', to='procurement.contract', verbose_name='Основной договор (для Доп. соглашений)')),
            ],
            options={
                'verbose_name': 'Договор',
                'verbose_name_plural': 'Реестр договоров',
                'ordering': ['-contract_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=512, unique=True, verbose_name='Полное наименование подразделения')),
                ('short_name', models.CharField(max_length=16, unique=True, verbose_name='Краткое наименование подразделения')),
                ('is_active', models.BooleanField(default=True, verbose_name='Действующее подразделение')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sub_departments', to='procurement.department', verbose_name='Вышестоящее подразделение (Агрегатор)')),
            ],
            options={
                'verbose_name': 'Подразделение',
                'verbose_name_plural': 'Подразделения',
                'ordering': ['short_name'],
            },
        ),
        migrations.CreateModel(
            name='EconomicClassifier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(db_index=True, max_length=32, unique=True, verbose_name='Код ЭКР (например, 1101008165)')),
                ('name', models.TextField(verbose_name='Наименование (расшифровка кода)')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sub_codes', to='procurement.economicclassifier', verbose_name='Вышестоящая статья/группа')),
            ],
            options={
                'verbose_name': 'Код ЭКР (Справочник)',
                'verbose_name_plural': 'Справочник кодов ЭКР',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='BudgetCosts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purchases_items_id', models.IntegerField(verbose_name='id позиции ГПЗ на goszakupki.by')),
                ('year', models.PositiveIntegerField(db_index=True, default=procurement.services.get_current_year, verbose_name='Год финансирования из бюджета')),
                ('cost', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Ориентировочная стоимость позиции ГПЗ')),
                ('department_code', models.CharField(blank=True, max_length=16, null=True, verbose_name='Код ведомственной классификации')),
                ('budget_code', models.IntegerField(default='90000', verbose_name='Код бюджета позиции плана')),
                ('budget_code_name', models.CharField(default='Республиканский бюджет', max_length=255, verbose_name='Описание кода бюджета')),
                ('unk', models.CharField(blank=True, default='1534', max_length=32, null=True, verbose_name='УНК заказчика позиции')),
                ('tk_id', models.IntegerField(blank=True, default='104', null=True, verbose_name='Код территориального казначейства')),
                ('economic_article', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='article_costs', to='procurement.economicclassifier', verbose_name='Статья (Уровень 4)')),
                ('economic_class', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='budget_costs', to='procurement.economicclassifier', verbose_name='Экономический код расходов (ЭКР)')),
                ('economic_kind', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='kind_costs', to='procurement.economicclassifier', verbose_name='Вид (Уровень 3)')),
                ('economic_section', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='section_costs', to='procurement.economicclassifier', verbose_name='Раздел (Уровень 1)')),
                ('economic_subsection', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='subsection_costs', to='procurement.economicclassifier', verbose_name='Подраздел (Уровень 2)')),
                ('external_economic_class', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='budget_costs', to='procurement.externaleconomiccode', verbose_name='Внешний код ЭКР')),
                ('functional_class', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='budget_costs', to='procurement.functionalcode', verbose_name='Функциональная классификация')),
            ],
            options={
                'verbose_name': 'Бюджетное финансирование',
                'verbose_name_plural': 'Бюджетное финансирование',
            },
        ),
        migrations.CreateModel(
            name='PlanShare',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shared_amount', models.DecimalField(decimal_places=3, default=0, max_digits=12, verbose_name='Количество для подразделения')),
                ('shared_cost', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Сумма для подразделения (BYN)')),
                ('budget_cost', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shares', to='procurement.budgetcosts', verbose_name='Годовое финансирование закупки')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='plan_shares', to='procurement.department', verbose_name='Подразделение ГКСЭ')),
            ],
            options={
                'verbose_name': 'Внутреннее распределение по подразделениям',
                'verbose_name_plural': 'Внутреннее распределение по подразделениям',
            },
        ),
        migrations.CreateModel(
            name='ContractItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveIntegerField(db_index=True, default=procurement.services.get_current_year, verbose_name='Год позиции договора')),
                ('contract_amount', models.DecimalField(decimal_places=3, max_digits=12, verbose_name='Количество по договору')),
                ('contract_cost', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Сумма по договору')),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='procurement.contract')),
                ('plan_share', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='contract_items', to='procurement.planshare')),
            ],
            options={
                'verbose_name': 'Спецификация к договору',
                'verbose_name_plural': 'Спецификация к договору',
                'ordering': ['-year', '-id'],
            },
        ),
        migrations.CreateModel(
            name='PlanVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('changed_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('DRAFT', 'Черновик (Редактирование)'), ('DRAFT_ON_REVIEW', 'На проверке у финансиста'), ('DRAFT_APPROVED', 'Одобрен финансистом'), ('DRAFT_REJECTED', 'Отклонен финансистом'), ('UPLOAD', 'Загружен на площадку'), ('ACTIVE', 'Актуальный (Доступен для договоров)'), ('ARCHIVE', 'В архиве')], db_index=True, default='DRAFT', max_length=20, verbose_name='Статус')),
                ('purchases_item_id', models.BigIntegerField(blank=True, null=True, verbose_name='id позиции ГПЗ на goszakupki.by')),
                ('purchases_id', models.BigIntegerField(blank=True, db_index=True, null=True, verbose_name='Идентификатор ГПЗ на goszakupki.by')),
                ('unp_budget', models.CharField(db_index=True, default='102377498', max_length=16, verbose_name='УНП')),
                ('num', models.CharField(db_index=True, max_length=32, verbose_name='Регистрационный номер позиции ГПЗ на goszakupki.by')),
                ('title', models.TextField(verbose_name='Наименование позиции ГПЗ на goszakupki.by')),
                ('okrb', models.CharField(db_index=True, max_length=16, verbose_name='Код ОКРБ 007 позиции ГПЗ на goszakupki.by')),
                ('okrb_title', models.TextField(verbose_name='Наименование позиции ГПЗ на goszakupki.by')),
                ('type', models.CharField(choices=[('job', 'работа/услуга'), ('product', 'товар')], default='product', max_length=32, verbose_name='Вид предмета закупки для позиции ГПЗ на goszakupki.by')),
                ('val_amount', models.DecimalField(decimal_places=3, default=0, max_digits=12, verbose_name='Объем закупки позиции ГПЗ на goszakupki.by')),
                ('val_type', models.CharField(db_index=True, max_length=8, verbose_name='Код ОКРБ 008 позиции ГПЗ на goszakupki.by')),
                ('fund_cost', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Цена позиции ГПЗ за счет средств внебюджетных фондов на goszakupki.by')),
                ('inner_cost', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Цена позиции ГПЗ за счет средств собственных средств на goszakupki.by')),
                ('val_currency', models.CharField(choices=[('BYN', 'Белорусский рубль (BYN)'), ('RUB', 'Российский рубль (RUB)'), ('USD', 'Доллар США (USD)'), ('EUR', 'Евро (EUR)'), ('CNY', 'Китайский юань (CNY)')], default='BYN', max_length=3, verbose_name='Валюта позиции ГПЗ на goszakupki.by')),
                ('procedure_months', models.JSONField(default=list, verbose_name='Список месяцев (от 1 до 12), в которые проводится процедура')),
                ('is_by_organizator', models.BooleanField(default=False, verbose_name='Отметка о проведении закупки организатором на goszakupki.by')),
                ('okrb_product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='plan_item_versions', to='procurement.okrbproduct', verbose_name='Продукция по ОКРБ 007')),
                ('planitem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='procurement.plan')),
                ('val_unit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='plan_item_versions', to='procurement.unitofmeasurement', verbose_name='Единица измерения')),
            ],
            options={
                'verbose_name': 'Пункт плана закупки',
                'verbose_name_plural': 'Пункты плана закупок',
                'ordering': ['-id'],
            },
        ),
        migrations.AddField(
            model_name='budgetcosts',
            name='plan_version',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='budget_costs', to='procurement.planversion', verbose_name='Версия пункта плана'),
        ),
        migrations.CreateModel(
            name='ProcurementMethodDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Например: 'ОИ по пункту 26 (Коммунальные услуги)' или 'Электронный аукцион'", max_length=512, verbose_name='Наименование процедуры / пункта')),
                ('is_active', models.BooleanField(default=True, verbose_name='Актуальный метод')),
                ('parent', models.ForeignKey(blank=True, help_text="Оставьте пустым, если это верхнеуровневый метод (например, просто 'Закупка из одного источника')", null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sub_methods', to='procurement.procurementmethoddetail', verbose_name='Родительский метод закупки')),
            ],
            options={
                'verbose_name': 'Детализация процедуры закупки',
                'verbose_name_plural': 'Справочник процедур закупок (с пунктами)',
                'ordering': ['parent_id', 'name'],
            },
        ),
        migrations.AddField(
            model_name='contract',
            name='procurement_method_detail',
            field=models.ForeignKey(blank=True, help_text='Выбор конкретного пункта процедуры из ведомственного справочника РБ', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='contracts', to='procurement.procurementmethoddetail', verbose_name='Вид процедуры закупки (Пункт)'),
        ),
        migrations.AddField(
            model_name='budgetcosts',
            name='program_class',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='budget_costs', to='procurement.programcode', verbose_name='Программная классификация'),
        ),
        migrations.AddField(
            model_name='plan',
            name='purchase',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='procurement.purchases'),
        ),
        migrations.AddField(
            model_name='contract',
            name='supplier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='contracts', to='procurement.supplier', verbose_name='Исполнитель/Поставщик'),
        ),
        migrations.CreateModel(
            name='TreasuryPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_number', models.CharField(blank=True, help_text='Внутренний номер платежки из системы Клиент-ТК Минфина', max_length=32, null=True, verbose_name='Номер платежного поручения')),
                ('payment_date', models.DateField(db_index=True, default=procurement.services.get_current_date, verbose_name='Дата оплаты')),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Сумма оплаты')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='procurement.contract', verbose_name='Договор')),
            ],
            options={
                'verbose_name': 'Платежное поручение',
                'verbose_name_plural': 'Реестр фактических оплат (Платежки)',
                'ordering': ['-payment_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ContractQuarterlyFinance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quarter', models.CharField(choices=[('Q1', 'I Квартал'), ('Q2', 'II Квартал'), ('Q3', 'III Квартал'), ('Q4', 'IV Квартал')], db_index=True, max_length=2, verbose_name='Квартал')),
                ('year', models.PositiveIntegerField(db_index=True, default=procurement.services.get_current_year, verbose_name='Год')),
                ('planned_cost', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Прогнозируемый (планируемый) расход')),
                ('actual_cost', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Фактический расход (по платежным поручениям)')),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quarterly_finances', to='procurement.contract', verbose_name='Договор')),
            ],
            options={
                'verbose_name': 'Квартальное финансирование договора',
                'verbose_name_plural': 'Квартальное финансирование договоров',
                'ordering': ['year', 'quarter'],
                'constraints': [models.UniqueConstraint(fields=('contract', 'quarter', 'year'), name='unique_contract_quarter_per_year')],
            },
        ),
        migrations.AddConstraint(
            model_name='plan',
            constraint=models.UniqueConstraint(condition=models.Q(('is_public', True), ('num__isnull', False)), fields=('num',), name='unique_num_for_public_plans'),
        ),
    ]
