# Generated by Django 6.0.5 on 2026-06-02 11:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=512, unique=True, verbose_name='Полное наименование подразделения')),
                ('short_name', models.CharField(max_length=16, unique=True, verbose_name='Краткое наименование подразделения')),
                ('is_active', models.BooleanField(default=True, verbose_name='Действующее подразделение')),
            ],
            options={
                'verbose_name': 'Подразделение',
                'verbose_name_plural': 'Подразделения',
                'ordering': ['short_name'],
            },
        ),
        migrations.CreateModel(
            name='EconomicClassifier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(db_index=True, max_length=32, unique=True, verbose_name='Код ЭКР (например, 1101008165)')),
                ('name', models.TextField(verbose_name='Наименование (расшифровка кода)')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sub_codes', to='procurement.economicclassifier', verbose_name='Вышестоящая статья/группа')),
            ],
            options={
                'verbose_name': 'Код ЭКР (Справочник)',
                'verbose_name_plural': 'Справочник кодов ЭКР',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='BudgetCosts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purchases_items_id', models.IntegerField(verbose_name='id позиции ГПЗ на goszakupki.by')),
                ('year', models.PositiveIntegerField(db_index=True, verbose_name='Год финансирования из бюджета')),
                ('cost', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Ориентировочная стоимость позиции ГПЗ')),
                ('functional_code', models.CharField(blank=True, max_length=32, null=True, verbose_name='Код функциональной классификации')),
                ('department_code', models.CharField(blank=True, max_length=16, null=True, verbose_name='Код ведомственной классификации')),
                ('economic_code', models.CharField(blank=True, choices=[('1 10 01 0', '1.10.01.00 Заработная плата'), ('1 10 02 99', '1.10.02.99 Начисления на зар. плату'), ('1 10 03 99', '1.10.03.99 Приобретение предметов снабжения и расходных материалов'), ('1 10 04 99', '1.10.04.99 Командировки'), ('1 10 05 0', '1.10.05.00 Оплата транспортных услуг'), ('1 10 06 0', '1.10.06.00 Оплата услуг связи'), ('1 10 07 99', '1.10.07.99 Оплата коммунальных услуг'), ('1 10 10 99', '1.10.10.99 Прочие текущие расходы'), ('1 30 03 99', '1.30.03.99 Текущие трансферты'), ('2 40 01 0', '2.40.01.00 Приобретение оборудования и других основных средств'), ('2 40 03 0', '2.40.03.00 Капитальный ремонт')], max_length=64, null=True, verbose_name='Код экономической классификация (ЭКР) (внешний)')),
                ('program_code', models.CharField(blank=True, max_length=16, null=True, verbose_name='Код программной классификации')),
                ('budget_code', models.IntegerField(default=90000, verbose_name='Код бюджета позиции плана')),
                ('budget_code_name', models.CharField(default='Республиканский бюджет', max_length=255, verbose_name='Описание кода бюджета')),
                ('unk', models.CharField(blank=True, max_length=32, null=True, verbose_name='УНК заказчика позиции')),
                ('tk_id', models.IntegerField(blank=True, null=True, verbose_name='Код территориального казначейства')),
                ('economic_article', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='article_costs', to='procurement.economicclassifier', verbose_name='Статья (Уровень 4)')),
                ('economic_class', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='all_budget_costs', to='procurement.economicclassifier', verbose_name='Экономический код расходов (ЭКР)')),
                ('economic_kind', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='kind_costs', to='procurement.economicclassifier', verbose_name='Вид (Уровень 3)')),
                ('economic_section', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='section_costs', to='procurement.economicclassifier', verbose_name='Раздел (Уровень 1)')),
                ('economic_subsection', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='subsection_costs', to='procurement.economicclassifier', verbose_name='Подраздел (Уровень 2)')),
            ],
            options={
                'verbose_name': 'Бюджетное финансирование',
                'verbose_name_plural': 'Бюджетное финансирование',
            },
        ),
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num', models.CharField(blank=True, db_index=True, max_length=64, null=True, verbose_name='Регистрационный номер позиции ГПЗ на goszakupki.by')),
                ('is_public', models.BooleanField(db_index=True, default=True, verbose_name='Публикуется на goszakupki.by')),
                ('status', models.CharField(choices=[('DRAFT', 'Черновик (Редактирование)'), ('ON_REVIEW', 'На проверке у финансиста'), ('ACTIVE', 'Утвержден (Доступен для договоров)'), ('PUBLISHED', 'Опубликован на goszakupki.by'), ('REJECTED', 'Отклонен финансистом'), ('DELETED', 'Исключен')], db_index=True, default='DRAFT', max_length=20, verbose_name='Статус')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Пункт плана закупки (мастер-запись)',
                'verbose_name_plural': 'Пункты плана закупок (мастер-записи)',
                'constraints': [models.UniqueConstraint(condition=models.Q(('is_public', True), ('num__isnull', False)), fields=('num',), name='unique_num_for_public_plans')],
            },
        ),
        migrations.CreateModel(
            name='PlanShare',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shared_amount', models.DecimalField(decimal_places=3, default=0.0, max_digits=12, verbose_name='Количество для подразделения')),
                ('shared_cost', models.DecimalField(decimal_places=2, default=0.0, max_digits=15, verbose_name='Сумма лимитов для подразделения (BYN)')),
                ('budget_cost', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shares', to='procurement.budgetcosts', verbose_name='Годовое финансирование закупки')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='plan_shares', to='procurement.department', verbose_name='Подразделение ГКСЭ')),
            ],
            options={
                'verbose_name': 'Внутреннее распределение по подразделениям',
                'verbose_name_plural': 'Внутреннее распределение по подразделениям',
            },
        ),
        migrations.CreateModel(
            name='PlanVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version_number', models.PositiveIntegerField(default=1, verbose_name='Номер версии')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='Актуальная версия')),
                ('plan_goszakupki_id', models.BigIntegerField(blank=True, null=True, verbose_name='id позиции ГПЗ на goszakupki.by')),
                ('purchases_id', models.BigIntegerField(blank=True, db_index=True, null=True, verbose_name='Идентификатор ГПЗ на goszakupki.by')),
                ('unp_budget', models.CharField(db_index=True, max_length=16, verbose_name='УНП')),
                ('title', models.TextField(verbose_name='Наименование позиции ГПЗ на goszakupki.by')),
                ('okrb', models.CharField(db_index=True, max_length=16, verbose_name='Код ОКРБ 007 позиции ГПЗ на goszakupki.by')),
                ('okrb_title', models.TextField(verbose_name='Наименование позиции ГПЗ на goszakupki.by')),
                ('type', models.CharField(choices=[('job', 'работа/услуга'), ('product', 'товар')], default='product', max_length=32, verbose_name='Вид предмета закупки для позиции ГПЗ на goszakupki.by')),
                ('val_amount', models.DecimalField(decimal_places=3, default=0, max_digits=12, verbose_name='Объем закупки позиции ГПЗ на goszakupki.by')),
                ('val_type', models.CharField(choices=[('0006', 'м'), ('0018', 'пог.м'), ('0055', 'м2'), ('0112', 'л'), ('0113', 'м3'), ('0116', 'дал'), ('0163', 'г'), ('0166', 'кг'), ('0231', 'мл'), ('0233', 'Гкал'), ('0245', 'кВт·ч'), ('0625', 'лист.'), ('0642', 'ед.'), ('0704', 'набор'), ('0715', 'пар'), ('0728', 'пач.'), ('0736', 'рул.'), ('0778', 'упак.'), ('0796', 'шт.'), ('0839', 'компл.'), ('0868', 'бут'), ('0870', 'ампул.'), ('0876', 'усл. ед.')], default='0642', max_length=16, verbose_name='Код ОКРБ 008 позиции ГПЗ на goszakupki.by')),
                ('fund_cost', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Цена позиции ГПЗ за счет средств внебюджетных фондов на goszakupki.by')),
                ('inner_cost', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Цена позиции ГПЗ за счет средств собственных средств на goszakupki.by')),
                ('val_currency', models.CharField(choices=[('BYN', 'Белорусский рубль (BYN)'), ('RUB', 'Российский рубль (RUB)'), ('USD', 'Доллар США (USD)'), ('EUR', 'Евро (EUR)'), ('CNY', 'Китайский юань (CNY)')], default='BYN', max_length=3, verbose_name='Валюта позиции ГПЗ на goszakupki.by')),
                ('procedure_months', models.JSONField(default=list, verbose_name='Список месяцев (от 1 до 12), в которые проводится процедура')),
                ('is_by_organizator', models.BooleanField(default=False, verbose_name='Отметка о проведении закупки организатором на goszakupki.by')),
                ('changed_at', models.DateTimeField(auto_now_add=True)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='procurement.plan')),
            ],
            options={
                'verbose_name': 'Пункт плана закупки',
                'verbose_name_plural': 'Пункты плана закупок',
                'ordering': ['-id'],
            },
        ),
        migrations.AddField(
            model_name='budgetcosts',
            name='plan_version',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='budget_costs', to='procurement.planversion', verbose_name='Версия пункта плана'),
        ),
    ]
