# Generated by Django 6.0.5 on 2026-06-19 18:34

import procurement.services.get_current_datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procurement', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Plan',
            new_name='PlanItem',
        ),
        migrations.RenameModel(
            old_name='PlanVersion',
            new_name='PlanItemVersion',
        ),
        migrations.AlterField(
            model_name='contract',
            name='contract_date',
            field=models.DateField(db_index=True, default=procurement.services.get_current_date, verbose_name='Дата заключения договора'),
        ),
    ]
