# Generated by Django 6.0.5 on 2026-06-22 15:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procurement', '0002_rename_plan_planitem_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='budgetcosts',
            name='plan_version',
        ),
        migrations.AddField(
            model_name='budgetcosts',
            name='plan_item',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='budget_costs', to='procurement.planitem', verbose_name='Версия пункта плана'),
        ),
        migrations.AlterField(
            model_name='budgetcosts',
            name='economic_class',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='budget_costs', to='procurement.economicclassifier', verbose_name='Экономический код расходов (ЭКР)'),
        ),
    ]
