# Generated by Django 6.0.5 on 2026-06-22 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procurement', '0003_remove_budgetcosts_plan_version_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='planitemversion',
            old_name='planitem',
            new_name='plan_item',
        ),
        migrations.AddField(
            model_name='budgetcosts',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Черновик (Редактирование)'), ('DRAFT_ON_REVIEW', 'На проверке у финансиста'), ('DRAFT_APPROVED', 'Одобрен финансистом'), ('DRAFT_REJECTED', 'Отклонен финансистом'), ('UPLOAD', 'Загружен на площадку'), ('ACTIVE', 'Актуальный (Доступен для договоров)'), ('ARCHIVE', 'В архиве')], db_index=True, default='DRAFT', max_length=20, verbose_name='Статус'),
        ),
    ]
