# Generated by Django 6.0.5 on 2026-06-02 16:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procurement', '0003_functionalcode_programcode_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExternalEconomicCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code_api', models.CharField(db_index=True, max_length=64, unique=True, verbose_name="Код в формате API (например, '1 10 10 99')")),
                ('description', models.TextField(verbose_name="Наименование статьи (например, '1.10.06.00 Оплата услуг связи')")),
                ('is_active', models.BooleanField(default=True, verbose_name='Действующий код')),
            ],
            options={
                'verbose_name': 'Внешний код ЭКР',
                'verbose_name_plural': 'Справочник внешних кодов ЭКР',
                'ordering': ['code_api'],
            },
        ),
        migrations.RemoveField(
            model_name='budgetcosts',
            name='economic_code',
        ),
        migrations.AddField(
            model_name='budgetcosts',
            name='external_economic_class',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='budget_costs', to='procurement.externaleconomiccode', verbose_name='Внешний код ЭКР'),
        ),
    ]
