# Generated by Django 6.0.5 on 2026-06-02 16:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procurement', '0004_externaleconomiccode_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=64, verbose_name='Номер договора')),
                ('total_cost', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Общая сумма договора')),
            ],
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=512, verbose_name='Наименование организации')),
                ('unp', models.CharField(db_index=True, max_length=9, unique=True, verbose_name='УНП (9 знаков)')),
            ],
            options={
                'verbose_name': 'Поставщик',
                'verbose_name_plural': 'Справочник поставщиков',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ContractItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contract_amount', models.DecimalField(decimal_places=3, max_digits=12, verbose_name='Количество по договору')),
                ('contract_cost', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Сумма по договору')),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='procurement.contract')),
                ('plan_share', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='procurement.planshare')),
            ],
        ),
        migrations.AddField(
            model_name='contract',
            name='supplier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='contracts', to='procurement.supplier', verbose_name='Исполнитель/Поставщик'),
        ),
    ]
