# Generated by Django 6.0.5 on 2026-06-22 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procurement', '0004_rename_planitem_planitemversion_plan_item_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='planitem',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True, verbose_name='Активная позиция?'),
        ),
        migrations.AlterField(
            model_name='planitem',
            name='is_public',
            field=models.BooleanField(db_index=True, default=True, verbose_name='Публикуется на goszakupki.by?'),
        ),
    ]
