# Generated by Django 6.0.5 on 2026-06-02 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procurement', '0005_contract_supplier_contractitem_contract_supplier'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supplier',
            name='unp',
            field=models.CharField(db_index=True, max_length=16, unique=True, verbose_name='УНП (9 знаков)'),
        ),
    ]
