# Generated by Django 6.0.5 on 2026-06-25 01:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procurement', '0005_alter_planitem_is_active_alter_planitem_is_public'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlanItemDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('changed_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('DRAFT', 'Черновик (Редактирование)'), ('DRAFT_ON_REVIEW', 'На проверке у финансиста'), ('DRAFT_APPROVED', 'Одобрен финансистом'), ('DRAFT_REJECTED', 'Отклонен финансистом'), ('UPLOAD', 'Загружен на площадку'), ('ACTIVE', 'Актуальный (Доступен для договоров)'), ('ARCHIVE', 'В архиве')], db_index=True, default='DRAFT', max_length=20, verbose_name='Статус')),
                ('purchases_item_id', models.BigIntegerField(blank=True, null=True, verbose_name='id позиции ГПЗ на goszakupki.by')),
                ('purchases_id', models.BigIntegerField(blank=True, db_index=True, null=True, verbose_name='Идентификатор ГПЗ на goszakupki.by')),
                ('unp_budget', models.CharField(db_index=True, default='102377498', max_length=16, verbose_name='УНП')),
                ('num', models.CharField(db_index=True, max_length=32, verbose_name='Регистрационный номер позиции ГПЗ на goszakupki.by')),
                ('title', models.TextField(verbose_name='Наименование позиции ГПЗ на goszakupki.by')),
                ('okrb', models.CharField(db_index=True, max_length=16, verbose_name='Код ОКРБ 007 позиции ГПЗ на goszakupki.by')),
                ('okrb_title', models.TextField(verbose_name='Наименование позиции ГПЗ на goszakupki.by')),
                ('type', models.CharField(choices=[('job', 'работа/услуга'), ('product', 'товар')], default='product', max_length=32, verbose_name='Вид предмета закупки для позиции ГПЗ на goszakupki.by')),
                ('val_amount', models.DecimalField(decimal_places=3, default=0, max_digits=12, verbose_name='Объем закупки позиции ГПЗ на goszakupki.by')),
                ('val_type', models.CharField(db_index=True, max_length=8, verbose_name='Код ОКРБ 008 позиции ГПЗ на goszakupki.by')),
                ('fund_cost', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Цена позиции ГПЗ за счет средств внебюджетных фондов на goszakupki.by')),
                ('inner_cost', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Цена позиции ГПЗ за счет средств собственных средств на goszakupki.by')),
                ('val_currency', models.CharField(choices=[('BYN', 'Белорусский рубль (BYN)'), ('RUB', 'Российский рубль (RUB)'), ('USD', 'Доллар США (USD)'), ('EUR', 'Евро (EUR)'), ('CNY', 'Китайский юань (CNY)')], default='BYN', max_length=3, verbose_name='Валюта позиции ГПЗ на goszakupki.by')),
                ('procedure_months', models.JSONField(default=list, verbose_name='Список месяцев (от 1 до 12), в которые проводится процедура')),
                ('is_by_organizator', models.BooleanField(default=False, verbose_name='Отметка о проведении закупки организатором на goszakupki.by')),
                ('okrb_product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='plan_item_versions', to='procurement.okrbproduct', verbose_name='Продукция по ОКРБ 007')),
                ('plan_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='details', to='procurement.planitem')),
                ('val_unit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='plan_item_versions', to='procurement.unitofmeasurement', verbose_name='Единица измерения')),
            ],
            options={
                'verbose_name': 'Пункт плана закупки',
                'verbose_name_plural': 'Пункты плана закупок',
                'ordering': ['-id'],
            },
        ),
        migrations.DeleteModel(
            name='PlanItemVersion',
        ),
    ]
