# Generated by Django 6.0.5 on 2026-06-25 01:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procurement', '0006_planitemdetail_delete_planitemversion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='planitem',
            name='purchase',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='items', to='procurement.purchases'),
        ),
        migrations.AlterField(
            model_name='planitemdetail',
            name='plan_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='details', to='procurement.planitem'),
        ),
    ]
