# Generated by Django 6.0.5 on 2026-06-03 09:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procurement', '0006_alter_supplier_unp'),
    ]

    operations = [
        migrations.CreateModel(
            name='OkrbProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(db_index=True, max_length=32, unique=True, verbose_name='Код ОКРБ 007 (например, 62.01.11.900)')),
                ('title', models.TextField(verbose_name='Наименование группировки/вида продукции')),
                ('is_active', models.BooleanField(default=True, verbose_name='Актуальный код')),
            ],
            options={
                'verbose_name': 'Код ОКРБ 007',
                'verbose_name_plural': 'Справочник ОКРБ 007',
                'ordering': ['code'],
            },
        ),
        migrations.AlterField(
            model_name='supplier',
            name='unp',
            field=models.CharField(db_index=True, max_length=16, unique=True, verbose_name='УНП'),
        ),
        migrations.AddField(
            model_name='planversion',
            name='okrb_product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='plan_versions', to='procurement.okrbproduct', verbose_name='Продукция по ОКРБ 007'),
        ),
    ]
