# Generated by Django 6.0.5 on 2026-06-25 02:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procurement', '0007_alter_planitem_purchase_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='budgetcosts',
            name='plan_item',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='budget_costs', to='procurement.planitem', verbose_name='Версия пункта плана'),
        ),
    ]
