# Generated by Django 6.0.5 on 2026-06-25 02:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('procurement', '0008_alter_budgetcosts_plan_item'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='externaleconomiccode',
            options={'ordering': ['code_api'], 'verbose_name': 'Код ЭКР (goszakupki.by)', 'verbose_name_plural': 'Справочник ЭКР (goszakupki.by)'},
        ),
        migrations.RenameField(
            model_name='budgetcosts',
            old_name='economic_class',
            new_name='economic_class_internal',
        ),
    ]
