# Generated by Django 6.0.5 on 2026-06-03 14:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('procurement', '0008_unitofmeasurement_alter_planversion_val_type_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='unitofmeasurement',
            old_name='code_api',
            new_name='code',
        ),
    ]
