# Generated by Django 6.0.5 on 2026-06-25 02:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('procurement', '0009_alter_externaleconomiccode_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='budgetcosts',
            old_name='external_economic_class',
            new_name='economic_class',
        ),
    ]
