# Generated by Django 6.0.5 on 2026-06-08 10:08

import datetime
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procurement', '0009_rename_code_api_unitofmeasurement_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='Buyer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shot_name', models.CharField(db_index=True, max_length=64, unique=True, verbose_name='Фамилия и инициалы')),
                ('full_name', models.CharField(db_index=True, max_length=128, unique=True, verbose_name='ФИО полностью')),
            ],
        ),
        migrations.AlterModelOptions(
            name='contract',
            options={'ordering': ['-contract_date', '-created_at'], 'verbose_name': 'Договор', 'verbose_name_plural': 'Реестр договоров'},
        ),
        migrations.AddField(
            model_name='contract',
            name='construction_type',
            field=models.CharField(blank=True, max_length=2048, null=True, verbose_name='Вид строительных работ / Объект строительства'),
        ),
        migrations.AddField(
            model_name='contract',
            name='contract_date',
            field=models.DateField(db_index=True, default=datetime.date(2026, 6, 8), verbose_name='Дата заключения договора'),
        ),
        migrations.AddField(
            model_name='contract',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contract',
            name='fixed_assets_plan_item',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Пункт перечня плана основных средств'),
        ),
        migrations.AddField(
            model_name='contract',
            name='is_registered_in_treasury',
            field=models.BooleanField(db_index=True, default=False, verbose_name='Регистрация в территориальном казначействе'),
        ),
        migrations.AddField(
            model_name='contract',
            name='notice',
            field=models.TextField(blank=True, null=True, verbose_name='Примечание / Дополнительная информация'),
        ),
        migrations.AddField(
            model_name='contract',
            name='parent_contract',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='main_agreements', to='procurement.contract', verbose_name='Основной договор (для Доп. соглашений)'),
        ),
        migrations.AddField(
            model_name='contract',
            name='payment_terms',
            field=models.CharField(blank=True, max_length=2048, null=True, verbose_name='Условия оплаты'),
        ),
        migrations.AddField(
            model_name='contract',
            name='planned_delivery_date',
            field=models.DateField(db_index=True, default=django.utils.timezone.now, verbose_name='Плановая дата поставки / выполнения работ / оказания услуг'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contract',
            name='procurement_method_detail',
            field=models.CharField(blank=True, help_text='Вид процедуры. Например: ОИ по пункту 26', max_length=50, null=True, verbose_name='Вид процедуры закупки (с детализацией пунктов)'),
        ),
        migrations.AddField(
            model_name='contractitem',
            name='year',
            field=models.PositiveIntegerField(db_index=True, default=2026, verbose_name='Год позиции договора'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='planversion',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='planversion',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='planshare',
            name='shared_cost',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=15, verbose_name='Сумма для подразделения (BYN)'),
        ),
        migrations.AddField(
            model_name='contract',
            name='buyer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='buyer_contracts', to='procurement.buyer', verbose_name='Закупщик'),
        ),
    ]
