# Generated by Django 6.0.5 on 2026-06-25 02:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('procurement', '0010_rename_external_economic_class_budgetcosts_economic_class'),
    ]

    operations = [
        migrations.RenameField(
            model_name='budgetcosts',
            old_name='economic_article',
            new_name='internal_economic_article',
        ),
        migrations.RenameField(
            model_name='budgetcosts',
            old_name='economic_class_internal',
            new_name='internal_economic_class',
        ),
        migrations.RenameField(
            model_name='budgetcosts',
            old_name='economic_kind',
            new_name='internal_economic_kind',
        ),
        migrations.RenameField(
            model_name='budgetcosts',
            old_name='economic_section',
            new_name='internal_economic_section',
        ),
        migrations.RenameField(
            model_name='budgetcosts',
            old_name='economic_subsection',
            new_name='internal_economic_subsection',
        ),
    ]
