# Generated by Django 6.0.5 on 2026-06-25 02:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('procurement', '0011_rename_economic_article_budgetcosts_internal_economic_article_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='EconomicClassifier',
            new_name='InternalEconomicClassifier',
        ),
    ]
