# Generated by Django 6.0.5 on 2026-06-25 02:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('procurement', '0012_rename_economicclassifier_internaleconomicclassifier'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='externaleconomiccode',
            options={'ordering': ['code_api'], 'verbose_name': 'Код ЭКР (goszakupki.by)', 'verbose_name_plural': 'Справочник кодов ЭКР (goszakupki.by)'},
        ),
        migrations.AlterModelOptions(
            name='internaleconomicclassifier',
            options={'ordering': ['code'], 'verbose_name': 'Код ЭКР (внутренний ГКСЭ)', 'verbose_name_plural': 'Справочник кодов ЭКР (внутренний ГКСЭ)'},
        ),
    ]
