# Generated by Django 6.0.5 on 2026-06-29 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procurement', '0013_alter_externaleconomiccode_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClosedPlanSequence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveIntegerField(unique=True)),
                ('current_counter', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Счетчик закрытых закупок',
                'verbose_name_plural': 'Счетчики закрытых закупок',
            },
        ),
        migrations.AlterModelOptions(
            name='planitemdetail',
            options={'ordering': ['-id'], 'verbose_name': 'Пункт плана закупки (детальная информация)', 'verbose_name_plural': 'Пункты плана закупок (детальная информация)'},
        ),
        migrations.AddField(
            model_name='treasurypayment',
            name='notice',
            field=models.CharField(blank=True, help_text='Примечание', max_length=1024, null=True, verbose_name='Примечание'),
        ),
        migrations.AddConstraint(
            model_name='planitem',
            constraint=models.UniqueConstraint(condition=models.Q(('is_public', False), ('num__isnull', False)), fields=('num',), name='unique_num_for_closed_plans'),
        ),
    ]
