# Generated by Django 6.0.5 on 2026-06-08 14:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procurement', '0013_alter_contractitem_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProcurementMethodDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Например: 'ОИ по пункту 26 (Коммунальные услуги)' или 'Электронный аукцион'", max_length=512, verbose_name='Наименование процедуры / пункта')),
                ('is_active', models.BooleanField(default=True, verbose_name='Актуальный метод')),
                ('parent', models.ForeignKey(blank=True, help_text="Оставьте пустым, если это верхнеуровневый метод (например, просто 'Закупка из одного источника')", null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sub_methods', to='procurement.procurementmethoddetail', verbose_name='Родительский метод закупки')),
            ],
            options={
                'verbose_name': 'Детализация процедуры закупки',
                'verbose_name_plural': 'Справочник процедур закупок (с пунктами)',
                'ordering': ['parent_id', 'name'],
            },
        ),
        migrations.AlterField(
            model_name='contract',
            name='procurement_method_detail',
            field=models.ForeignKey(blank=True, help_text='Выбор конкретного пункта процедуры из ведомственного справочника РБ', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='contracts', to='procurement.procurementmethoddetail', verbose_name='Вид процедуры закупки (Пункт)'),
        ),
    ]
