# Generated by Django 6.0.5 on 2026-06-12 09:31

import datetime
import django.db.models.deletion
import procurement.models.budgetCosts
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procurement', '0014_procurementmethoddetail_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='planversion',
            name='updated_at',
        ),
        migrations.AlterField(
            model_name='budgetcosts',
            name='budget_code',
            field=models.IntegerField(default='90000', verbose_name='Код бюджета позиции плана'),
        ),
        migrations.AlterField(
            model_name='budgetcosts',
            name='economic_class',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='budget_costs', to='procurement.economicclassifier', verbose_name='Экономический код расходов (ЭКР)'),
        ),
        migrations.AlterField(
            model_name='budgetcosts',
            name='tk_id',
            field=models.IntegerField(blank=True, default='104', null=True, verbose_name='Код территориального казначейства'),
        ),
        migrations.AlterField(
            model_name='budgetcosts',
            name='unk',
            field=models.CharField(blank=True, default='1534', max_length=32, null=True, verbose_name='УНК заказчика позиции'),
        ),
        migrations.AlterField(
            model_name='budgetcosts',
            name='year',
            field=models.PositiveIntegerField(db_index=True, default=procurement.models.budgetCosts.get_current_year, verbose_name='Год финансирования из бюджета'),
        ),
        migrations.AlterField(
            model_name='contractitem',
            name='year',
            field=models.PositiveIntegerField(db_index=True, default=2026, verbose_name='Год позиции договора'),
        ),
        migrations.AlterField(
            model_name='contractquarterlyfinance',
            name='year',
            field=models.PositiveIntegerField(db_index=True, default=2026, verbose_name='Год'),
        ),
        migrations.AlterField(
            model_name='planversion',
            name='unp_budget',
            field=models.CharField(db_index=True, default='102377498', max_length=16, verbose_name='УНП'),
        ),
        migrations.AlterField(
            model_name='treasurypayment',
            name='payment_date',
            field=models.DateField(db_index=True, default=datetime.datetime(2026, 6, 12, 9, 31, 22, 156807, tzinfo=datetime.timezone.utc), verbose_name='Дата оплаты'),
        ),
    ]
