# Generated by Django 6.0.5 on 2026-06-29 09:50

import procurement.services.get_current_datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procurement', '0014_closedplansequence_alter_planitemdetail_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='treasurypayment',
            name='quarter',
            field=models.CharField(choices=[('Q1', 'I Квартал'), ('Q2', 'II Квартал'), ('Q3', 'III Квартал'), ('Q4', 'IV Квартал')], db_index=True, default='Q1', max_length=2, verbose_name='Квартал'),
        ),
        migrations.AlterField(
            model_name='treasurypayment',
            name='payment_date',
            field=models.DateField(db_index=True, default=procurement.services.get_current_date(), verbose_name='Дата разнесения платежа'),
        ),
    ]
