# Generated by Django 6.0.5 on 2026-06-12 09:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procurement', '0015_remove_planversion_updated_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='treasurypayment',
            name='payment_date',
            field=models.DateField(db_index=True, default=datetime.datetime(2026, 6, 12, 9, 31, 52, 129332, tzinfo=datetime.timezone.utc), verbose_name='Дата оплаты'),
        ),
    ]
