# Generated by Django 6.0.5 on 2026-06-29 09:54

import procurement.services
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procurement', '0015_treasurypayment_quarter_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='treasurypayment',
            name='payment_date',
            field=models.DateField(db_index=True, default=procurement.services.get_current_date(), verbose_name='Дата разнесения платежа'),
        ),
    ]
