# Generated by Django 6.0.5 on 2026-06-29 12:52

import procurement.services.get_current_datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procurement', '0016_alter_treasurypayment_payment_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='internaleconomicclassifier',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Действующий код'),
        ),
        migrations.AlterField(
            model_name='treasurypayment',
            name='payment_date',
            field=models.DateField(db_index=True, default=procurement.services.get_current_date(), verbose_name='Дата разнесения платежа'),
        ),
    ]
