# Generated by Django 6.0.5 on 2026-06-30 14:10

import django.utils.timezone
import procurement.services.get_current_datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procurement', '0019_alter_treasurypayment_payment_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='budgetcosts',
            name='changed_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='budgetcosts',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='treasurypayment',
            name='payment_date',
            field=models.DateField(db_index=True, default=procurement.services.get_current_date(), verbose_name='Дата разнесения платежа'),
        ),
    ]
