# Generated by Django 6.0.5 on 2026-07-01 07:17

import procurement.services.get_current_datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procurement', '0020_budgetcosts_changed_at_budgetcosts_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='budgetcosts',
            name='economic_code',
            field=models.CharField(blank=True, max_length=32, null=True, verbose_name='Экономический код goszakupki.by'),
        ),
        migrations.AddField(
            model_name='budgetcosts',
            name='functional_code',
            field=models.CharField(blank=True, max_length=32, null=True, verbose_name='Функциональный код goszakupki.by'),
        ),
        migrations.AddField(
            model_name='budgetcosts',
            name='program_code',
            field=models.CharField(blank=True, max_length=16, null=True, verbose_name='Программный код goszakupki.by'),
        ),
        migrations.AlterField(
            model_name='budgetcosts',
            name='status',
            field=models.CharField(choices=[('ACTIVE', 'Актуальный (Доступен для договоров)'), ('DRAFT', 'Черновик (Редактирование)'), ('EXCLUSION', 'Запланирован к исключению из плана'), ('DRAFT_ON_REVIEW', 'На проверке у финансиста'), ('EXCLUSION_ON_REVIEW', 'На проверке у финансиста'), ('DRAFT_APPROVED', 'Одобрен финансистом'), ('EXCLUSION_APPROVED', 'Одобрен финансистом'), ('DRAFT_REJECTED', 'Отклонен финансистом'), ('EXCLUSION_REJECTED', 'Отклонен финансистом'), ('UPLOAD', 'Загружен на площадку'), ('ARCHIVE', 'В архиве')], db_index=True, default='DRAFT', max_length=20, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='planitemdetail',
            name='status',
            field=models.CharField(choices=[('ACTIVE', 'Актуальный (Доступен для договоров)'), ('DRAFT', 'Черновик (Редактирование)'), ('EXCLUSION', 'Запланирован к исключению из плана'), ('DRAFT_ON_REVIEW', 'На проверке у финансиста'), ('EXCLUSION_ON_REVIEW', 'На проверке у финансиста'), ('DRAFT_APPROVED', 'Одобрен финансистом'), ('EXCLUSION_APPROVED', 'Одобрен финансистом'), ('DRAFT_REJECTED', 'Отклонен финансистом'), ('EXCLUSION_REJECTED', 'Отклонен финансистом'), ('UPLOAD', 'Загружен на площадку'), ('ARCHIVE', 'В архиве')], db_index=True, default='DRAFT', max_length=20, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='treasurypayment',
            name='payment_date',
            field=models.DateField(db_index=True, default=procurement.services.get_current_date, verbose_name='Дата разнесения платежа'),
        ),
    ]
