# Generated by Django 6.0.5 on 2026-07-01 07:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procurement', '0021_budgetcosts_economic_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='planitem',
            name='purchase',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='items', to='procurement.purchases'),
        ),
    ]
