# Generated by Django 6.0.5 on 2026-07-01 08:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('procurement', '0022_alter_planitem_purchase'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='planitem',
            name='purchase',
        ),
    ]
