# Generated by Django 6.0.5 on 2026-07-01 08:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procurement', '0023_remove_planitem_purchase'),
    ]

    operations = [
        migrations.AddField(
            model_name='planitem',
            name='purchase',
            field=models.ForeignKey(default=8, on_delete=django.db.models.deletion.PROTECT, to='procurement.purchases'),
            preserve_default=False,
        ),
    ]
