# Generated by Django 6.0.5 on 2026-07-01 08:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('procurement', '0024_planitem_purchase'),
    ]

    operations = [
        migrations.RenameField(
            model_name='planitem',
            old_name='purchase',
            new_name='plan_purchase',
        ),
    ]
