# Generated by Django 6.0.5 on 2026-07-06 08:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procurement', '0025_rename_purchase_planitem_plan_purchase'),
    ]

    operations = [
        migrations.AddField(
            model_name='planshare',
            name='plan_item',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, related_name='plan_shares', to='procurement.planitemdetail', verbose_name='Пункт плана закупки'),
        ),
        migrations.AddField(
            model_name='planshare',
            name='status',
            field=models.CharField(choices=[('ACTIVE', 'Актуальный (Доступен для договоров)'), ('DRAFT', 'Черновик (Редактирование)'), ('EXCLUSION', 'Запланирован к исключению из плана'), ('DRAFT_ON_REVIEW', 'На проверке у финансиста'), ('EXCLUSION_ON_REVIEW', 'На проверке у финансиста'), ('DRAFT_APPROVED', 'Одобрен финансистом'), ('EXCLUSION_APPROVED', 'Одобрен финансистом'), ('DRAFT_REJECTED', 'Отклонен финансистом'), ('EXCLUSION_REJECTED', 'Отклонен финансистом'), ('UPLOAD', 'Загружен на площадку'), ('ARCHIVE', 'В архиве')], db_index=True, default='ACTIVE', max_length=20, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='planshare',
            name='budget_cost',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='plan_shares', to='procurement.budgetcosts', verbose_name='Финансирование по пункту плана закупки'),
        ),
    ]
