# Generated by Django 6.0.5 on 2026-07-06 08:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procurement', '0026_planshare_plan_item_planshare_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='planshare',
            name='plan_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='plan_shares', to='procurement.planitemdetail', verbose_name='Пункт плана закупки'),
        ),
    ]
