# Generated by Django 6.0.5 on 2026-07-06 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procurement', '0027_alter_planshare_plan_item'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='planshare',
            name='plan_item',
        ),
        migrations.AlterField(
            model_name='budgetcosts',
            name='status',
            field=models.CharField(choices=[('ACTIVE', 'Актуальный (Доступен для договоров)'), ('DRAFT', 'Черновик (изменения)'), ('EXCLUSION', 'Черновик (исключение)'), ('DRAFT_ON_REVIEW', 'На проверке у финансиста (изменение)'), ('EXCLUSION_ON_REVIEW', 'На проверке у финансиста (исключение)'), ('DRAFT_APPROVED', 'Одобрен финансистом (изменение)'), ('EXCLUSION_APPROVED', 'Одобрен финансистом (исключение)'), ('DRAFT_REJECTED', 'Отклонен финансистом (изменение)'), ('EXCLUSION_REJECTED', 'Отклонен финансистом (исключение)'), ('UPLOAD', 'Загружен на площадку'), ('ARCHIVE', 'В архиве')], db_index=True, default='DRAFT', max_length=20, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='planitemdetail',
            name='status',
            field=models.CharField(choices=[('ACTIVE', 'Актуальный (Доступен для договоров)'), ('DRAFT', 'Черновик (изменения)'), ('EXCLUSION', 'Черновик (исключение)'), ('DRAFT_ON_REVIEW', 'На проверке у финансиста (изменение)'), ('EXCLUSION_ON_REVIEW', 'На проверке у финансиста (исключение)'), ('DRAFT_APPROVED', 'Одобрен финансистом (изменение)'), ('EXCLUSION_APPROVED', 'Одобрен финансистом (исключение)'), ('DRAFT_REJECTED', 'Отклонен финансистом (изменение)'), ('EXCLUSION_REJECTED', 'Отклонен финансистом (исключение)'), ('UPLOAD', 'Загружен на площадку'), ('ARCHIVE', 'В архиве')], db_index=True, default='DRAFT', max_length=20, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='planshare',
            name='status',
            field=models.CharField(choices=[('ACTIVE', 'Актуальный (Доступен для договоров)'), ('DRAFT', 'Черновик (изменения)'), ('EXCLUSION', 'Черновик (исключение)'), ('DRAFT_ON_REVIEW', 'На проверке у финансиста (изменение)'), ('EXCLUSION_ON_REVIEW', 'На проверке у финансиста (исключение)'), ('DRAFT_APPROVED', 'Одобрен финансистом (изменение)'), ('EXCLUSION_APPROVED', 'Одобрен финансистом (исключение)'), ('DRAFT_REJECTED', 'Отклонен финансистом (изменение)'), ('EXCLUSION_REJECTED', 'Отклонен финансистом (исключение)'), ('UPLOAD', 'Загружен на площадку'), ('ARCHIVE', 'В архиве')], db_index=True, default='ACTIVE', max_length=20, verbose_name='Статус'),
        ),
    ]
