# Generated by Django 6.0.5 on 2026-07-06 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procurement', '0028_remove_planshare_plan_item_alter_budgetcosts_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='planshare',
            name='shared_fund_cost',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Сумма для подразделения (внебюджетные фонды) (BYN)'),
        ),
        migrations.AddField(
            model_name='planshare',
            name='shared_inner_cost',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Сумма для подразделения (собственные средства) (BYN)'),
        ),
    ]
