# Generated by Django 6.0.5 on 2026-07-06 10:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procurement', '0029_planshare_shared_fund_cost_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contractitem',
            name='contract',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='items', to='procurement.contract'),
        ),
    ]
