# Generated by Django 6.0.5 on 2026-07-08 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procurement', '0030_alter_contractitem_contract'),
    ]

    operations = [
        migrations.AddField(
            model_name='contractitem',
            name='title',
            field=models.CharField(blank=True, max_length=2048, null=True, verbose_name='Наименование позиции, как в договоре'),
        ),
    ]
