# Generated by Django 6.0.5 on 2026-07-08 14:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procurement', '0031_contractitem_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='KindOfPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1024, unique=True, verbose_name='Название типа платежа')),
            ],
            options={
                'verbose_name': 'Тип платежа',
                'verbose_name_plural': 'Типы платежей',
                'ordering': ['-id'],
            },
        ),
        migrations.AlterField(
            model_name='treasurypayment',
            name='contract',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='procurement.contract', verbose_name='Договор'),
        ),
        migrations.AddField(
            model_name='treasurypayment',
            name='kind',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='procurement.kindofpayment', verbose_name='Вид платежа'),
        ),
    ]
