# Generated by Django 6.0.5 on 2026-07-08 14:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procurement', '0032_kindofpayment_alter_treasurypayment_contract_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='treasurypayment',
            name='economic_class',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='treasury_payments', to='procurement.externaleconomiccode', verbose_name='Внешний код ЭКР'),
        ),
        migrations.AddField(
            model_name='treasurypayment',
            name='functional_class',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='treasury_payments', to='procurement.functionalcode', verbose_name='Функциональная классификация'),
        ),
        migrations.AddField(
            model_name='treasurypayment',
            name='internal_economic_class',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='treasury_payments', to='procurement.internaleconomicclassifier', verbose_name='Экономический код расходов (ЭКР)'),
        ),
        migrations.AddField(
            model_name='treasurypayment',
            name='program_class',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='treasury_payments', to='procurement.programcode', verbose_name='Программная классификация'),
        ),
        migrations.AlterField(
            model_name='treasurypayment',
            name='contract',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='treasury_payments', to='procurement.contract', verbose_name='Договор'),
        ),
        migrations.AlterField(
            model_name='treasurypayment',
            name='kind',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='treasury_payments', to='procurement.kindofpayment', verbose_name='Вид платежа'),
        ),
    ]
