# Generated by Django 6.0.5 on 2026-07-09 08:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procurement', '0033_treasurypayment_economic_class_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='kindofpayment',
            options={'ordering': ['id'], 'verbose_name': 'Тип платежа', 'verbose_name_plural': 'Типы платежей'},
        ),
        migrations.AddField(
            model_name='planitemdetail',
            name='buyer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='plan_items', to='procurement.buyer', verbose_name='Закупщик'),
        ),
        migrations.AlterField(
            model_name='treasurypayment',
            name='kind',
            field=models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='treasury_payments', to='procurement.kindofpayment', verbose_name='Вид платежа'),
        ),
    ]
