# Generated by Django 6.0.5 on 2026-07-09 09:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procurement', '0034_alter_kindofpayment_options_planitemdetail_buyer_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='planitemdetail',
            name='buyer',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='plan_items', to='procurement.buyer', verbose_name='Закупщик'),
        ),
    ]
